### ISSUE TITLE
open config modal when clicking on an object

### ISSUE THREAD

**Issue by waspinator** [jsbroks/coco-annotator#100]

**Comment by jsbroks** [comment]
Could you elaborate a little more? Annotation object?

**Comment by waspinator** [comment]
when using the select tool, you can hover over objects to see their metadata. It would be useful if you could click on them to open their metadata modal (the modal that appears when clicking on their corresponding "gear" icon).

**Comment by jsbroks** [comment]
As of v0.5.8 the selected tool sets the currently selected annotation as the one clicked (#81). With the addition of a right-click menu (#83), this should be an option found there
