### ISSUE TITLE
add "refresh" button to datasets

### ISSUE THREAD

**Issue by waspinator** [jsbroks/coco-annotator#101]
a refresh button to re-scan directories is helpful for systems where the file watcher doesn't work

**Comment by jsbroks** [comment]
Have you found situations where the file watcher does not work?

**Comment by waspinator** [comment]
yes, on a mac

**Comment by jeroenroodnat** [comment]
File watcher breaks moving coco-annotator from Docker to Kubernetes. Would be nice to have an env setting to disable file watcher on boot.
