### ISSUE TITLE
Error Moving Images Within the Container

### ISSUE THREAD

**Issue by teclea** [jsbroks/coco-annotator#104]
The following error was received from within my dataset directory in the Coco Annotator UI: **"No images found in directory."** This error occurred after moving a temporary image folder into the dataset directory from within the container on a Ubuntu system. 

The following command was used in the interactive shell:
`$ sudo mv /data/datasets/temp/some_image_folder /data/datasets/SomeDataset/`

A shell running the annotator_flask container shows that the directory does contain the images moved, but does not reflect in the Coco Annotator UI.

**Comment by jsbroks** [comment]
Strange, once #101 is completed you can use the rescan function.
