### ISSUE TITLE
Implement DEXTR selection tool

### ISSUE THREAD

**Issue by jsbroks** [jsbroks/coco-annotator#114]
https://github.com/scaelles/DEXTR-PyTorch

**Comment by NicksonYap** [comment]
@jsbroks Yes, Please implement this, would be awesome!

Is there a branch/commit for this already?

**Comment by jsbroks** [comment]
@NicksonYap [Yes](https://github.com/jsbroks/coco-annotator/tree/feature/114-dextr-tool), the repo would also have to be converted into a python package so we can use it in coco-annotator. I created a repo for [here](https://github.com/jsbroks/dextrlib).

Would be greatly appreciated if you would like to help out
