### ISSUE TITLE
Does your coco annotator support keypoint ? 

### ISSUE THREAD

**Issue by intvo** [jsbroks/coco-annotator#118]
We need to train our model on bodypose, so does this annotator support keypoint? 
thank you

**Comment by jsbroks** [comment]
No, although this a feature I plan on implementing.

**Comment by intvo** [comment]
@jsbroks Thank you for your quick response, we really need this future very soon, can you update, we are willing to pay money to get it done sooner

**Comment by jsbroks** [comment]
@intvo Please email me at jsbroks@gmail.com for further inquiry

**Comment by intvo** [comment]
@jsbroks We did, please check your email

**Comment by jsbroks** [comment]
Created #119.
