### ISSUE TITLE
Keypoints

### ISSUE THREAD

**Issue by jsbroks** [jsbroks/coco-annotator#119]
- [x] Annotation of coco keypoints
  - [x] Create keypoint tool
    - [x] Vue tool component 
    - [x] Visualization logic
    - [x] Saving
    - [x] Loading
- [x] Category
  - [x] skeleton options
  - [x] keypoint options
- [x] Exporting of coco keypoints

**Comment by jsbroks** [comment]
@intvo Completed implementation, please let me know of any bugs

**Comment by intvo** [comment]
@jsbroks Can you change the setting for the keypoint to match the coco format 
class CocoPart(Enum):
    Nose = 0
    Neck = 1
    RShoulder = 2
    RElbow = 3
    RWrist = 4
    LShoulder = 5
    LElbow = 6
    LWrist = 7
    RHip = 8
    RKnee = 9
    RAnkle = 10
    LHip = 11
    LKnee = 12
    LAnkle = 13
    REye = 14
    LEye = 15
    REar = 16
    LEar = 17

**Comment by jsbroks** [comment]
@intvo You can set them using the settings of the category, or when you import using coco format they should automatically be set. If you manual enter them, make sure to import them in order from lowest index to highest

**Comment by intvo** [comment]
@jsbroks Thank you for your promote response when I run the application on my Mac, and i try to login, I'm facing issues. 
<img width="1224" alt="screen shot 2019-02-23 at 9 35 27 am" src="https://user-images.githubusercontent.com/40445787/53289024-699f1e80-375e-11e9-9a46-826339f9f471.png">

**Comment by jsbroks** [comment]
@intvo Is this the demo server?
username: admin
password: password
If not, the first time you ran the instance you should have set this information.

**Comment by intvo** [comment]
@jsbroks  When i run it on the local host, it doesn't work, also when i click register, it doesn't work either, please try to run it on your PC. 
<img width="1191" alt="screen shot 2019-02-23 at 11 35 34 am" src="https://user-images.githubusercontent.com/40445787/53289086-301ae300-375f-11e9-9082-0ee4701fb7f9.png">

**Comment by jsbroks** [comment]
@intvo Open another issue and I'll look into it.

**Comment by jsbroks** [comment]
@intvo Use mongodb compass and delete all users in the db.

**Comment by intvo** [comment]
Solved the issue. Thanks

**Comment by 1209805200** [comment]
@jsbroks hi,when i click the settings buttons on the category ,it didn't bring up the key points menu.and just like this.
![Selection_001](https://user-images.githubusercontent.com/39993135/54194622-9fcaf500-44f7-11e9-8512-366274d36b24.png)
i can only print some words in the box.
can you tell me what should i do to be the  demo serve show of the keypoint settings.
![Selection_002](https://user-images.githubusercontent.com/39993135/54194828-1d8f0080-44f8-11e9-835b-9be682e47a00.png)
i try my best to do this ,but there is nothing.
![Screenshot from 2019-03-12 18-37-58](https://user-images.githubusercontent.com/39993135/54194912-4b744500-44f8-11e9-85d1-fca378ed5c7b.png)
Looking forward to your reply.

**Comment by 1209805200** [comment]
@jsbroks hi,when i click the settings buttons on the category ,it didn't bring up the key points menu.
i can only print some words in “add a catagory”.
can you tell me what should i do to be the demo serve show of the keypoint settings.
how to set their?
(Nose = 0
    Neck = 1
    RShoulder = 2
    RElbow = 3
    RWrist = 4
    LShoulder = 5
    LElbow = 6
    LWrist = 7
    RHip = 8
    RKnee = 9
    RAnkle = 10
    LHip = 11
    LKnee = 12
    LAnkle = 13
    REye = 14
    LEye = 15
    REar = 16
    LEar = 17)

i try my best to do this ,but my keypoint don't have labels.

Looking forward to your reply.TAT

**Comment by jsbroks** [comment]
@1209805200 Add the keypoints in that order to the add a category section (naming is a spelling error). If you already placed keypoints down before adding a label you can double click on the keypoint to open a menu to change it

**Comment by 1209805200** [comment]
thank you!-3-
it is cool

**Comment by stlslm** [comment]
> @1209805200 Add the keypoints in that order to the add a category section (naming is a spelling error). If you already placed keypoints down before adding a label you can double click on the keypoint to open a menu to change it

Unfortunately, this does not work. After the double click, it shows the keypoint info with the label as an uneditable text. I cannot find a way to redefine the keypoint, either. I am testing on the master branch FYI

**Comment by prajwaljpj** [comment]
> 

Could you elaborate how we can reset the password using Mongo compass?

**Comment by anas-zafar** [comment]
@prajwaljpj were you able to solve it?
