### ISSUE TITLE
Next/Previous Image

### ISSUE THREAD

**Issue by jsbroks** [jsbroks/coco-annotator#12]
Add image navigation tools inside of the editor to go to the next or previous image in the dataset.

**Comment by chitraa** [comment]
The next and previous do not fetch the right images for subdirectories inside the dataset.

```
pre = images.filter(file_name__lt=image.file_name).order_by('-file_name').first()
nex = images.filter(file_name__gt=image.file_name).order_by('file_name').first()
```

This essentially fetches the next image in the dataset. However, when one is inside a *subdirectory* inside a dataset, this behavior is unexpected. One would expect to get the next image *in that subdirectory* when one clicks next (and not just the next image based on filename in the whole dataset)
