### ISSUE TITLE
Ability to create points or facial landmarks?

### ISSUE THREAD

**Issue by trinath503** [jsbroks/coco-annotator#120]
Is there a way to add points on the images for facial landmarks as shown in the image below:
![9bugr](https://user-images.githubusercontent.com/19545163/53067758-b46d2c00-34fb-11e9-8b6f-8979e70a3e65.png)
@jsbroks

**Comment by jsbroks** [comment]
Hello @trinath503, COCO keypoints is currently a work in progress #119. The progress can be viewed on the keypoints [branch](https://github.com/jsbroks/coco-annotator/tree/keypoints).

**Comment by trinath503** [comment]
Unable to see key points data  in JSON response.
But in db its storing
![screenshot from 2019-02-26 18-55-30](https://user-images.githubusercontent.com/19545163/53415877-4db6a980-39f8-11e9-907d-eaca7999e4b0.png)


Here I added a point and downloaded JSON, but I can't see the point.
![screenshot from 2019-02-26 18-55-45](https://user-images.githubusercontent.com/19545163/53415878-4db6a980-39f8-11e9-93e9-4ea35f9fad35.png)

**Comment by trinath503** [comment]
Unable to see key points data  in JSON response.
But in db its storing
![screenshot from 2019-02-26 18-55-45](https://user-images.githubusercontent.com/19545163/53415878-4db6a980-39f8-11e9-93e9-4ea35f9fad35.png)


Here I added a point and downloaded JSON, but I can't see the point.

![screenshot from 2019-02-26 18-55-30](https://user-images.githubusercontent.com/19545163/53415877-4db6a980-39f8-11e9-907d-eaca7999e4b0.png)

**Comment by jsbroks** [comment]
@trinath503 Could you please open a new issue
