### ISSUE TITLE
Add members to admin account 

### ISSUE THREAD

**Issue by intvo** [jsbroks/coco-annotator#125]
Would you please add an option to add members to the admin account? these members will do the annotation tasks for the admin, also the admin can give them the option to download the annotation files if he chose too.

**Comment by jsbroks** [comment]
You can add users using the admin account. But the ability to specify if the user can download is not currently a feature.

**Comment by intvo** [comment]
Yes, I saw this future, but when I add a new user that the user can't see the dataset. 
-  hope you can allow the admin to not allow the user to download the annotation file which is the most important things if we do crowdsourcing

**Comment by jsbroks** [comment]
Clicking the dropdown and share, allows you to share datasets with other users.
