### ISSUE TITLE
KeyPoints Missing in JSON File

### ISSUE THREAD

**Issue by trinath503** [jsbroks/coco-annotator#126]
Unable to see key points data in JSON response.
But in DB its storing

![screenshot from 2019-02-26 18-55-45](https://user-images.githubusercontent.com/19545163/53467363-f5c18680-3a7b-11e9-9162-126b70d5cee8.png)

Here I added a point and downloaded JSON, but I can't see the point.

![screenshot from 2019-02-26 18-55-30](https://user-images.githubusercontent.com/19545163/53467365-fc4ffe00-3a7b-11e9-88ec-be38f462a576.png)

**Comment by jsbroks** [comment]
Are you exporting an image or a dataset?

**Comment by trinath503** [comment]
Exporting an image

**Comment by jsbroks** [comment]
Can you try the `lastest` tag and see if i fixed it

**Comment by trinath503** [comment]
sure i will let you know , shortly

**Comment by jsbroks** [comment]
Any update?

**Comment by trinath503** [comment]
@jsbroks It's Working fine
