### ISSUE TITLE
Missing annotation info when 'Download COCO' functionality is used

### ISSUE THREAD

**Issue by AdanMora** [jsbroks/coco-annotator#127]
Hello,

When I want to download all COCO json from a dataset, the annotation data is not included, any data or just some annotations. That happen in my local version as well.

![download_coco](https://user-images.githubusercontent.com/32461935/53492884-40ea9200-3a9a-11e9-8ace-abd16e26c189.png)

![image](https://user-images.githubusercontent.com/32461935/53493145-f289c300-3a9a-11e9-8089-a9ef320caac1.png)

Thanks.

**Comment by AdanMora** [comment]
Thanks!

**Comment by AdanMora** [comment]
@jsbroks you already fixed the bug? It still not working.

**Comment by jsbroks** [comment]
@AdanMora which build image as you using

**Comment by AdanMora** [comment]
Sorry, maybe is that, I'm not familiar with Docker, I did again the installation erasing the containers, I also tried the update commands in the wiki, but it still not working for me, in your online test annotator it works.

**Comment by jsbroks** [comment]
Every time I tag, a docker image called `stable` is built. Every time I make a commit, the `latest` tag is built.

On [line 7 in the docker-compose.yml](https://github.com/jsbroks/coco-annotator/blob/master/docker-compose.yml#L7) you want to switch it from `stable` to `latest`. Then..
```
docker-compose pull
docker-compose down
docker-compose up
```

**Comment by AdanMora** [comment]
I think my problem was that I was doing the Production Build, not the Development Build. I did those changes and it works, Thank you!!

**Comment by jsbroks** [comment]
I would just like to clarify, the `latest` is still a production build.

**Comment by AdanMora** [comment]
Ok, I tried to say that I built the project with:

`$ docker-compose -f docker-compose.dev.yml up --build`

and it works.

The other command didn't update the image:

`$ docker-compose up --build`

**Comment by jsbroks** [comment]
Did try what I did above?

> Every time I tag, a docker image called `stable` is built. Every time I make a commit, the `latest` tag is built.
> 
> On [line 7 in the docker-compose.yml](https://github.com/jsbroks/coco-annotator/blob/master/docker-compose.yml#L7) you want to switch it from `stable` to `latest` (at the end). Then..
> 
> ```
> docker-compose pull
> docker-compose down
> docker-compose up
> ```

**Comment by AdanMora** [comment]
Yes I did it but it doesn't work with the first command, only with the other one.

**Comment by jsbroks** [comment]
My bad the last `latest` build fail, thats why it didn't fix it
