### ISSUE TITLE
Can't download COCO annotation file after labeling 1k images

### ISSUE THREAD

**Issue by intvo** [jsbroks/coco-annotator#135]
When i try to download the annotation file, it failed ( failed - network error ) 
Please take a look at this issue as soon as possible. Thank you

**Comment by luxedo** [comment]
Is this solved? I'm having the same issue at `v0.10.5`.

**Comment by jsbroks** [comment]
Yes. Please provide more detail

**Comment by luxedo** [comment]
When I download the COCO file for a dataset that has 928 images I get a `Download Failed`message in chrome.

The request status code is 200 and I get a well formed JSON in the body, I think all the annotations are there.
![Screenshot from 2019-05-27 16-10-11](https://user-images.githubusercontent.com/14118472/58436240-bd414100-809a-11e9-91eb-65d09bb8e2ec.png)

I managed to download the file using `curl`.
