### ISSUE TITLE
Sharing of dataset is not working

### ISSUE THREAD

**Issue by trinath503** [jsbroks/coco-annotator#138]
After adding a user name in the share pop-up, the user is unable to see the dataset that was shared after login

![Screenshot from 2019-03-13 12-22-52](https://user-images.githubusercontent.com/19545163/54259211-fdf4e800-458a-11e9-9d54-5a00a85cd08e.png)

As far I know, the username is not been added in the dataset_model (database) in user array (after sharing also seems empty array)

![Screenshot from 2019-03-13 13-52-03](https://user-images.githubusercontent.com/19545163/54263596-35699180-4597-11e9-8c7b-f7fba6fa76a6.png)

![Screenshot from 2019-03-13 13-51-06](https://user-images.githubusercontent.com/19545163/54263566-1ff46780-4597-11e9-88bb-96522ed1a808.png)

**Comment by jsbroks** [comment]
Are you using the save button when you add a new users?

**Comment by trinath503** [comment]
Ya its working

**Comment by jsbroks** [comment]
Can this issue be closed?

**Comment by trinath503** [comment]
yes
