### ISSUE TITLE
coco-annotator_flask_1 exited with code 3

### ISSUE THREAD

**Issue by fuzzyBatman** [jsbroks/coco-annotator#146]
`sudo docker-compose up --build` gives the following output

Creating network "coco-annotator_default" with the default driver
Creating volume "coco-annotator_mongodb_data" with default driver
Creating annotator_mongodb ... done
Creating coco-annotator_flask_1 ... done
Attaching to annotator_mongodb, coco-annotator_flask_1
annotator_mongodb | chown: changing ownership of '/proc/1/fd/1': Permission denied
annotator_mongodb | chown: changing ownership of '/proc/1/fd/2': Permission denied
flask_1     | [2019-03-16 22:53:48 +0000] [9] [DEBUG] Current configuration:
flask_1     |   config: None
flask_1     |   bind: ['0.0.0.0:5000']
flask_1     |   backlog: 2048
flask_1     |   workers: 1
flask_1     |   worker_class: eventlet
flask_1     |   threads: 1
flask_1     |   worker_connections: 1000
flask_1     |   max_requests: 0
flask_1     |   max_requests_jitter: 0
flask_1     |   timeout: 180
flask_1     |   graceful_timeout: 30
flask_1     |   keepalive: 2
flask_1     |   limit_request_line: 4094
flask_1     |   limit_request_fields: 100
flask_1     |   limit_request_field_size: 8190
flask_1     |   reload: False
flask_1     |   reload_engine: auto
flask_1     |   reload_extra_files: []
flask_1     |   spew: False
flask_1     |   check_config: False
flask_1     |   preload_app: False
flask_1     |   sendfile: False
flask_1     |   reuse_port: False
flask_1     |   chdir: /workspace
flask_1     |   daemon: False
flask_1     |   raw_env: []
flask_1     |   pidfile: None
flask_1     |   worker_tmp_dir: None
flask_1     |   user: 0
flask_1     |   group: 0
flask_1     |   umask: 0
flask_1     |   initgroups: False
flask_1     |   tmp_upload_dir: None
flask_1     |   secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
flask_1     |   forwarded_allow_ips: ['127.0.0.1']
flask_1     |   accesslog: None
flask_1     |   disable_redirect_access_to_syslog: False
flask_1     |   access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
flask_1     |   errorlog: -
flask_1     |   loglevel: debug
flask_1     |   capture_output: False
flask_1     |   logger_class: gunicorn.glogging.Logger
flask_1     |   logconfig: None
flask_1     |   logconfig_dict: {}
flask_1     |   syslog_addr: udp://localhost:514
flask_1     |   syslog: False
flask_1     |   syslog_prefix: None
flask_1     |   syslog_facility: user
flask_1     |   enable_stdio_inheritance: False
flask_1     |   statsd_host: None
flask_1     |   statsd_prefix: 
flask_1     |   proc_name: None
flask_1     |   default_proc_name: app:app
flask_1     |   pythonpath: None
flask_1     |   paste: None
flask_1     |   on_starting: <function OnStarting.on_starting at 0x7fa9a3237158>
flask_1     |   on_reload: <function OnReload.on_reload at 0x7fa9a3237268>
flask_1     |   when_ready: <function WhenReady.when_ready at 0x7fa9a3237378>
flask_1     |   pre_fork: <function Prefork.pre_fork at 0x7fa9a3237488>
flask_1     |   post_fork: <function Postfork.post_fork at 0x7fa9a3237598>
flask_1     |   post_worker_init: <function PostWorkerInit.post_worker_init at 0x7fa9a32376a8>
flask_1     |   worker_int: <function WorkerInt.worker_int at 0x7fa9a32377b8>
flask_1     |   worker_abort: <function WorkerAbort.worker_abort at 0x7fa9a32378c8>
flask_1     |   pre_exec: <function PreExec.pre_exec at 0x7fa9a32379d8>
flask_1     |   pre_request: <function PreRequest.pre_request at 0x7fa9a3237ae8>
flask_1     |   post_request: <function PostRequest.post_request at 0x7fa9a3237b70>
flask_1     |   child_exit: <function ChildExit.child_exit at 0x7fa9a3237c80>
flask_1     |   worker_exit: <function WorkerExit.worker_exit at 0x7fa9a3237d90>
flask_1     |   nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fa9a3237ea0>
flask_1     |   on_exit: <function OnExit.on_exit at 0x7fa9a3240048>
flask_1     |   proxy_protocol: False
flask_1     |   proxy_allow_ips: ['127.0.0.1']
flask_1     |   keyfile: None
flask_1     |   certfile: None
flask_1     |   ssl_version: 2
flask_1     |   cert_reqs: 0
flask_1     |   ca_certs: None
flask_1     |   suppress_ragged_eofs: True
flask_1     |   do_handshake_on_connect: False
flask_1     |   ciphers: TLSv1
flask_1     |   raw_paste_global_conf: []
flask_1     | [2019-03-16 22:53:48 +0000] [9] [INFO] Starting gunicorn 19.9.0
flask_1     | [2019-03-16 22:53:48 +0000] [9] [DEBUG] Arbiter booted
flask_1     | [2019-03-16 22:53:48 +0000] [9] [INFO] Listening at: http://0.0.0.0:5000 (9)
flask_1     | [2019-03-16 22:53:48 +0000] [9] [INFO] Using worker: eventlet
flask_1     | [2019-03-16 22:53:48 +0000] [12] [INFO] Booting worker with pid: 12
flask_1     | [2019-03-16 22:53:48 +0000] [9] [DEBUG] 1 workers
flask_1     | [2019-03-16 22:53:49 +0000] [12] [ERROR] Exception in worker process
flask_1     | Traceback (most recent call last):
flask_1     |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
flask_1     |     worker.init_process()
flask_1     |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/geventlet.py", line 102, in init_process
flask_1     |     super(EventletWorker, self).init_process()
flask_1     |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
flask_1     |     self.load_wsgi()
flask_1     |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
flask_1     |     self.wsgi = self.app.wsgi()
flask_1     |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
flask_1     |     self.callable = self.load()
flask_1     |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
flask_1     |     return self.load_wsgiapp()
flask_1     |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
flask_1     |     return util.import_app(self.app_uri)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
flask_1     |     __import__(module)
flask_1     |   File "/workspace/app/__init__.py", line 49, in <module>
flask_1     |     app = create_app()
flask_1     |   File "/workspace/app/__init__.py", line 25, in create_app
flask_1     |     run_watcher()
flask_1     |   File "/workspace/app/watcher.py", line 51, in run_watcher
flask_1     |     observer.start()
flask_1     |   File "/usr/local/lib/python3.6/site-packages/watchdog/observers/api.py", line 255, in start
flask_1     |     emitter.start()
flask_1     |   File "/usr/local/lib/python3.6/site-packages/watchdog/utils/__init__.py", line 111, in start
flask_1     |     self.on_thread_start()
flask_1     |   File "/usr/local/lib/python3.6/site-packages/watchdog/observers/inotify.py", line 121, in on_thread_start
flask_1     |     self._inotify = InotifyBuffer(path, self.watch.is_recursive)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
flask_1     |     self._inotify = Inotify(path, recursive)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/watchdog/observers/inotify_c.py", line 187, in __init__
flask_1     |     self._add_dir_watch(path, recursive, event_mask)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/watchdog/observers/inotify_c.py", line 364, in _add_dir_watch
flask_1     |     self._add_watch(path, mask)
flask_1     |   File "/usr/local/lib/python3.6/site-packages/watchdog/observers/inotify_c.py", line 385, in _add_watch
flask_1     |     Inotify._raise_error()
flask_1     |   File "/usr/local/lib/python3.6/site-packages/watchdog/observers/inotify_c.py", line 406, in _raise_error
flask_1     |     raise OSError(os.strerror(err))
flask_1     | OSError: Permission denied
flask_1     | [2019-03-16 22:53:49 +0000] [12] [INFO] Worker exiting (pid: 12)
flask_1     | [2019-03-16 22:53:49 +0000] [9] [INFO] Shutting down: Master
flask_1     | [2019-03-16 22:53:49 +0000] [9] [INFO] Reason: Worker failed to boot.
coco-annotator_flask_1 exited with code 3

**Comment by fuzzyBatman** [comment]
Nvm. Fixed it.

**Comment by jsbroks** [comment]
Could you pleae share the solution for others

**Comment by fuzzyBatman** [comment]
Yeah. Sorry about that.

The issue was with **Docker** installation.
Had nothing to do with coco-annotator itself.

I deleted the container, created a _docker_ group and added myself (the user) to the group and ran the compose command again.

**Comment by playma** [comment]
I pull the latest code, then `docker-compose up`
Facing the same problem, can you help me to solve it>

**Comment by jsbroks** [comment]
Did you try what fuzzyBatman has suggested?

**Comment by DeepCNNs** [comment]
I am facing the same issue. I have already tried what fuzzyBatman suggested. Could you please help me resolve this.
