### ISSUE TITLE
Clearer instructions on getting setup

### ISSUE THREAD

**Issue by mveres01** [jsbroks/coco-annotator#15]
I had some slight difficulty getting started with the tool, as a few things were ambiguous. Maybe consider adding a few more detailed steps? For example, had to figure out that:

- You first have to create a dataset
- Then you have to create categories for the dataset
- Then you have to assign a category to the dataset (if you want multiple, you need to Ctrl + click or Shift + click all of the corresponding categories)
- Then you need to move images to the data/datasets/<created_dataset> folder. I found that moving images to this folder required sudo permission on linux

A simple enhancement could be to provide these steps as (for example) a right-hand panel on the main screen, or as a "reminder" bubble that pops up when creating a dataset

**Comment by jsbroks** [comment]
https://github.com/jsbroks/coco-annotator/wiki/Creating-a-Basic-Shape-Dataset
