### ISSUE TITLE
Zoom on high resolution images freezes

### ISSUE THREAD

**Issue by deep-jkl** [jsbroks/coco-annotator#151]
When zooming annotated image that has > 5000x5000 pixels resolution, the canvas stops working.

Browser:
 Firefox 65.0.1 (64-bit), Ubuntu 18.04
COCO annotator at https://annotator.justinbrooks.ca/

How to replicate
    Create a catagory, generate sample dataset ('high resolution' keyword),
    pick a brush tool, make some path, zoom in until canvas stops responding

**Comment by jsbroks** [comment]
This is a limitation of [paperjs](https://github.com/paperjs/paper.js) ([stackoverflow](https://stackoverflow.com/questions/25503708/view-zoom-is-rendering-slow-for-large-canvas-size-in-paper-js)). As mentioned in #150 try to limit the amount of keypoints.

Let me know if any of the follow could help with your us case:
 - All images will be resize to be no larger then 2000 and all annotations will then be scaled to match the original on save
 - A toggle option for CSS zooming. This would fix the performance issue but when you zoom it the quality would degrade and no component properties will be able to scale with zoom.

**Comment by jsbroks** [comment]
@deep-jkl Try using the latest build and see if that fixes your problem.

**Comment by deep-jkl** [comment]
Tried on latest docker image, the zoom->freeze issue is solved, but annotations are not transparent, is this intentional?

**Comment by jsbroks** [comment]
They should be still transparent, I did increase the transparency to 70% instead of 50%, since I remove the outline around the annotations

**Comment by jsbroks** [comment]
So it is a bug, when you load annotations they are transparent but once you apply an operation to them they become non-transparent. I'm closing this issue, since its not related. 

Please open a new one

**Comment by deep-jkl** [comment]
Thanks for fast response, I confirm your claim that annotations are loaded transparent but modifications causes lost of transparency. New issue #161
