### ISSUE TITLE
Slow loading of large datasets

### ISSUE THREAD

**Issue by deep-jkl** [jsbroks/coco-annotator#152]
When a dataset of roughly 26000 images was created, annotator took ~5 seconds to load a single image (saying 'loading annotations').

Browser:
Firefox 65.0.1 (64-bit), Ubuntu 18.04
Coco annotator docker image version 0.8.0.

Dataset info:
26000 images of resolution 270x320 pixels

**Comment by jsbroks** [comment]
Clauses is from getting [next a previous](https://github.com/jsbroks/coco-annotator/blob/181caecaeffc9dc80ce611ca0b7636062f4bc784/app/api/annotator.py#L130). Does anyone know a better way to do this?

**Comment by jsbroks** [comment]
@deep-jkl Could you check the latest build to see if the issue is fixed. I don't have a 26k dataset to test this on.

**Comment by deep-jkl** [comment]
Hi, 
sorry for the long delay, I have pulled newest image from dockerhub, the loading is now fine, but thumbnails are not shown, is this a feature or shall I fire another issue?

**Comment by jsbroks** [comment]
Yes, but please provide as much information as possible since Im not having this this problem

**Comment by deep-jkl** [comment]
I've created new issue with more info #170. Thanks.
