### ISSUE TITLE
Adding index number in keypoints

### ISSUE THREAD

**Issue by trinath503** [jsbroks/coco-annotator#156]
Add a text: which represents the nth point that created in key points.

It helps how many points are created for the user while adding points

**Comment by jsbroks** [comment]
Could you expand on this more, not quite sure what you mean?

**Comment by trinath503** [comment]
![Screenshot from 2019-03-25 11-27-15](https://user-images.githubusercontent.com/19545163/54898116-ff120780-4ef0-11e9-9291-a9a023ecac5b.png)

As you see the index number is showing in Labels, so can we show the index number inside the circle of keypoint only?

**Comment by jsbroks** [comment]
It should be showing the label name. Not the index number. What version are you on?

**Comment by trinath503** [comment]
ya, your right.
i was using older version : v0.7.0
