### ISSUE TITLE
not seeing how to create first annotation in UI

### ISSUE THREAD

**Issue by EMCP** [jsbroks/coco-annotator#158]
I have a data set, I click the image, I have already made a category....

where is the .. or how do I .. get annotations started?  all the brush tools are greyed out

<img width="700" alt="Screen Shot 2019-03-21 at 8 43 25 PM" src="https://user-images.githubusercontent.com/3691722/54780460-182d6680-4c1a-11e9-9da6-4019bd2e358d.png">

<img width="40" alt="Screen Shot 2019-03-21 at 8 58 19 PM" src="https://user-images.githubusercontent.com/3691722/54781272-182e6600-4c1c-11e9-8558-a7cc7fc47892.png">

**Comment by EMCP** [comment]
I understand now, that you in fact have to ENABLE .. categories.. this was not clear until further reading.  I think you need to have a warning when someone makes a dataset with zero categories enabled.. or just show ALL categories if non are selected... otherwise it's unclear why my categories don't show up

**Comment by jsbroks** [comment]
There is a section in the wiki `Adding Categories to an Existing Dataset`. If it's still not clear enough I recommend you put a PR in changing the texted display when a category is not in the image. Here is a link to the [section of code](https://github.com/jsbroks/coco-annotator/blob/7624bdbbd7545952d530542a35e1e66300b3cf7d/client/src/views/Annotator.vue#L114).

**Comment by EMCP** [comment]
sounds good, thank you for responding.

https://github.com/jsbroks/coco-annotator/pull/160
