### ISSUE TITLE
Duplicate keys in mongodb when dataset is deleted

### ISSUE THREAD

**Issue by mveres01** [jsbroks/coco-annotator#16]
Datasets are not properly getting deleted from the mongodb instance when deleted from the main tool. Steps to reproduce:

* Create a dataset **temp**
* Delete a dataset **temp**
* Create a dataset **temp**

```mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error collection: flask.dataset_model index: name_1 dup key: {  : "temp"})```

edit: add dataset name "temp"

**Comment by jsbroks** [comment]
There are two types of deletions, partial and full. When you use the interface to delete any of the objects (categories, datasets and annotations) it sets a flag saying the object has been deleted.  You can then navigate to the Undo tab found in the navigation bar. Here you can view all partial deletions and undo or fully delete the object from the database.

More information about this feature will be added to the documentation. Once #10 is completed a popup will be used to inform the user it is partially deleted.

**Comment by mveres01** [comment]
Makes sense, thanks.

Along these same lines, the undo feature doesn't seem to be working at the moment. 

Same process of: 
- Create dataset **temp**
- Delete dataset **temp**
- Select Undo from navigation bar

> annotator_flask |   File "/workspace/flask/app/models.py", line 120, in __init__
> annotator_flask |     raise ValueError("Invalid image id.")
> annotator_flask | ValueError: Invalid image id.

**Comment by jsbroks** [comment]
With the instructions you have provided I am not able to reproduce this issue.

**Comment by mveres01** [comment]
I'm not able to reproduce it this morning either. Weird. Thanks!
