### ISSUE TITLE
DEXTR is disabled in v0.8.0 Demo

### ISSUE THREAD

**Issue by NicksonYap** [jsbroks/coco-annotator#163]
Hey @jsbroks 

I realise the DEXTR is disabled in annotator.justinbrooks.ca

Is it because it takes too much processing power to run the demo?

Hosting fees etc

Or is it that CUDA is needed?
Server Hardware issues, etc

Regards,

Nickson

**Comment by jsbroks** [comment]
It takes 20 seconds to call on one annotation. Takes to much cpu power

**Comment by NicksonYap** [comment]
Yeah, I suppose, just curious, what hosting provided do you use for the demo?
