### ISSUE TITLE
Addition of additional tools - RectangularBox!

### ISSUE THREAD

**Issue by face-palm** [jsbroks/coco-annotator#164]
It'd be terrific if we could get some additional tools, in particular a rectangle box and circle.

**Comment by jsbroks** [comment]
Can you use the brush tool for circles?

**Comment by face-palm** [comment]
Possibly; rectangular tool really is the key thing tbh.

**Comment by raphael0202** [comment]
Rectangular box is also a must-have for my use case

**Comment by jin-cheng-li** [comment]
Rectangular box is needed for my use case too. Many labeling tasks use rectangular box.
