### ISSUE TITLE
Connection lost opening large images (>3 MB)

### ISSUE THREAD

**Issue by face-palm** [jsbroks/coco-annotator#166]
When trying to open large files in the datasets a “Connection Lost” error in the GUI is seen. Backend log looks like this

> flask_1     | [2019-03-27 20:50:20 +0000] [242] [DEBUG] GET /api/image/9
flask_1     | [2019-03-27 20:50:20 +0000] [242] [DEBUG] GET /socket.io/
flask_1     | [2019-03-27 20:50:22 +0000] [251] [INFO] Booting worker with pid: 251
flask_1     | MaskRCNN model is disabled.
flask_1     | DEXTR model is disabled.
flask_1     | [2019-03-27 20:50:23 +0000] [251] [DEBUG] GET /socket.io/
flask_1     | [2019-03-27 20:50:23 +0000] [251] [DEBUG] GET /api/image/9
flask_1     | [2019-03-27 20:50:23 +0000] [251] [DEBUG] GET /socket.io/
flask_1     | [2019-03-27 20:50:24 +0000] [260] [INFO] Booting worker with pid: 260
flask_1     | MaskRCNN model is disabled.
flask_1     | DEXTR model is disabled.
flask_1     | [2019-03-27 20:50:26 +0000] [260] [DEBUG] GET /socket.io/
flask_1     | [2019-03-27 20:50:26 +0000] [260] [DEBUG] GET /api/image/9
flask_1     | [2019-03-27 20:50:26 +0000] [260] [DEBUG] POST /api/annotator/data
flask_1     | [2019-03-27 20:50:27 +0000] [269] [INFO] Booting worker with pid: 269
flask_1     | MaskRCNN model is disabled.

Is this a file size issue? A timeout somewhere?

Browser:
Safari 12.1 (64-bit) - OSX 10.14.4
Running on Ubuntu 18.04 via Lightsail instance
CocoAnnotator v.0.8.0

**Comment by jsbroks** [comment]
I tested it on a [4MB image](https://upload.wikimedia.org/wikipedia/commons/1/1e/Caerte_van_Oostlant_4MB.jpg) and it loaded fine. The Lightsail instance might not be powerful enough? There is a timeout on the thread but which is currently set to 3 mins.

**Comment by face-palm** [comment]
I'll set up a slightly higher performing instance and see what happens there.

**Comment by jsbroks** [comment]
@face-palm Any updates?

**Comment by face-palm** [comment]
Yup, a better instance greatly improved it. Not sure what the sweet spot is between cost and performance but if anyone reads this playing around with the $20 lightstail instances works great (4GB memory, 2 CPU, 80GB SSD).
