### ISSUE TITLE
Run coco-annotator on my own server

### ISSUE THREAD

**Issue by walaceapolo** [jsbroks/coco-annotator#168]
Hi Jsbroks,

I would like to know if it's possible to run coco-annotator on my own server like you did? What can I do to reach that? Needs to be a python server? If you could provide some light, it would help.

Thank you for your time.

**Comment by jsbroks** [comment]
Please follow the instructions for installation found on the [wiki](https://github.com/jsbroks/coco-annotator/wiki/Getting-Started).

Install docker and make sure the ports are open.

**Comment by walaceapolo** [comment]
Hi, thanks for your reply.

I've been able to make everything work on my localhost following the steps you provided, but the question is how can I make it work in the cloud, like you did here: https://annotator.justinbrooks.ca/

Thanks for your time.

**Comment by jsbroks** [comment]
Its running on a VPS. Purchase a vps/dedicated server from any provider and set it up how you did it locally.

**Comment by walaceapolo** [comment]
Cool, I'm going to try!

Thanks again!
