### ISSUE TITLE
annotator_mongodb exited with code 100

### ISSUE THREAD

**Issue by AdanMora** [jsbroks/coco-annotator#172]
Hi @jsbroks 

I have a rare problem with one of my coco-annotator instances, the mongo image or container just stop working, now if I try to put up the annotator, it raise this error on the log console:

![error100_1](https://user-images.githubusercontent.com/32461935/55243726-1843ec80-5240-11e9-9dd6-f6e4faffa916.png)

I removed all the images and containers related to mongo and coco-annotator, I reinstalled everything but it doesn't work on my server, but my personal instance on my computer works without problem, did you or someone experience something similar?

Thanks.

**Comment by jsbroks** [comment]
Have not seen this before. May try cleaning all docker images?

**Comment by AdanMora** [comment]
I already did it and it doesn't works, it's really strange, it has to by the computer because in other computer it works perfectly.

**Comment by jsbroks** [comment]
Removing all docker images and doing a fresh pull resolved the issue. Not sure the cause. This can be reopened if we can find a way to reproduce it.
