### ISSUE TITLE
when running on ubuntu, cannot see png images

### ISSUE THREAD

**Issue by EMCP** [jsbroks/coco-annotator#180]
I've tried and tried to see any pngs while running this off Ubuntu 18.04... does this webapp support pngs?

**Comment by EMCP** [comment]
confirmed that it worked when running on a mac, but not on an ubuntu machine.

**Comment by jsbroks** [comment]
What version are you using?

**Comment by jsbroks** [comment]
Running 0.10.0 on Ubuntu 18.04 using PNG images works fine for me.

**Comment by EMCP** [comment]
Can you just repeat the exact steps you took?  Wondering if it's a file
permissions issue.

**Comment by jsbroks** [comment]
1. Downloaded a PNG file from google
2. Placed it in a dataset folder
3. Checked the logs to see if File Watcher registered it
4. Opened it up in the annotator

How large is this file?

**Comment by EMCP** [comment]
2880x1880 pngs ranging from 1.3MB to 8MB

**Comment by EMCP** [comment]
being having a few unrelated issues centering the image as I annotate (on Mac OSX where it works to a certain degree)

**Comment by face-palm** [comment]
@EMCP I too can load PNG images just fine on 0.9.0. I had previously had issues loading images, turned out the instance I was running on was just too low in spec (needs more CPU/RAM).

The file I just tried was: https://i.redd.it/d8tymon8yhk21.png (5.4 MB).

As an FYI, the instance I'm no longer having issues running this on is an AWS Lightsail instance with 4 GB RAM, 2 vCPUs, 80 GB SSD.

**Comment by jsbroks** [comment]
@EMCP Can we close this

**Comment by EMCP** [comment]
@jsbroks let's go ahead, I will upgrade to latest as per other ticket conversation and retry.  https://github.com/jsbroks/coco-annotator/issues/82#issuecomment-480963578 thanks for the steps!

**Comment by EMCP** [comment]
I tried again with latest build... `v0.10.2`.  Downloaded latest docker, `docker-compose up` and dragged and dropped a folder into the `datset/` area.  Nothing happened on the VueJS side.. but I saw the watcher picking up files... then I tried to create a blank dataset and drag the images manually into that....

looks like a permissions issue... I cannot copy paste images INTO the folder, it has a little lock symbol on it.  This leads me to believe it's a permissions issue.  Please advise.

**Comment by jsbroks** [comment]
Related to #165 ?

**Comment by EMCP** [comment]
Probably, I'm not following what the fix or work around is exactly...

**Comment by jsbroks** [comment]
@face-palm posted a solution in the issue. Permissions to the dataset folder isn't related to PNG images loading
