### ISSUE TITLE
unclear how to export entire dataset with annotations 

### ISSUE THREAD

**Issue by EMCP** [jsbroks/coco-annotator#183]
I have a test dataset, which I have fully annotated to a degree i think should work.. now I want to export that entire dataset.. and only now realized that each image needs to be cycled through by hand and exported?  Is that correct?  Or is there a button somewhere to export an entire dataset?

**Comment by EMCP** [comment]
When I used the dataset level button, it only downloads one single coco file .. I'm a little confused as the regular coco dataset creates individual json files.. no?

**Comment by jsbroks** [comment]
Dataset creates one large coco json file. You can click the Export button from the dropdown menu of a dataset. Or for very large datasets use the export button found in the dataset view

**Comment by EMCP** [comment]
I guess I will look at the one coming out.. this is my first time building a COCO style dataset and want to try and shoe-horn it through this implementation of FASTER RCNN https://github.com/jwyang/faster-rcnn.pytorch will just give it a shot and reopen if issues

thanks!
