### ISSUE TITLE
Non standard fields in dataset COCO export

### ISSUE THREAD

**Issue by raphael0202** [jsbroks/coco-annotator#184]
When exporting a dataset, non standard fields can be found in the export:
```json
{"images":[{"id":1,"dataset_id":1,"category_ids":[1],"path":"/datasets/nutrition-table/0076208003907_1.jpg","width":3120,"height":4208,"file_name":"0076208003907_1.jpg","annotated":false,"annotating":[],"metadata":{},"milliseconds":1099251,"events":[{"_cls":"SessionEvent","user":"raphael0202","milliseconds":7528,"tools_used":[]},{"_cls":"SessionEvent","user":"raphael0202","milliseconds":1091723,"tools_used":[]}],"regenerate_thumbnail":false}],"categories":[{"id":1,"name":"nutrition-table","supercategory":"","color":"#7b01ce","metadata":{},"creator":"raphael0202"}],"annotations":[]}
```

`events`, `user` or `milliseconds` are not standard COCO fields.

**Comment by jsbroks** [comment]
Also, `dataset_id`, `category_ids`, `path`, `annotated`, and `metadata`. As long as the required fields are in the JSON it doesn't matter what else is there.

**Comment by raphael0202** [comment]
Ok thanks, I'm using the latest docker version.

**Comment by jsbroks** [comment]
@raphael0202 On the top left in webpage what version does it say?

**Comment by jsbroks** [comment]
@raphael0202 How are you exporting? Using the datasets dropdown menu?

**Comment by raphael0202** [comment]
@jsbroks v 0.10.2, exporting using the dataset dropdown menu.

**Comment by jsbroks** [comment]
Dropdown export is deprecated and once I completed the exports page inside the dataset view, it will be removed. Try using the export button instead the datasets view. It will create a` coco.json` file in the root of the datasets directory.
