### ISSUE TITLE
Running on vps server

### ISSUE THREAD

**Issue by walaceapolo** [jsbroks/coco-annotator#185]
Hi, after I've purchased a vps server to run my coco-annotator privately in the web (vpsserver.com) running on CENTOS 7.4 x64, what are the steps to get it running with a public ip or domain like you did it here: https://annotator.justinbrooks.ca/
I runned "docker pull jsbroks/coco-annotator" in the console command and "docker run -d -P --name coco jsbroks/coco-annotator". Can you help me with the next steps, please?

**Comment by jsbroks** [comment]
I'm using [letsencrypt and nigix](https://hub.docker.com/r/linuxserver/letsencrypt/) docker image to handle the subdomain and `https`. 
I recommend you use `docker-compose` commands instead of `docker` to get the coco-annotator running. Installing is the same process as installing locally and instruction are on the wiki. 

I haven't tested any of this on CentOS but it should work fine.

**Comment by jsbroks** [comment]
https://github.com/jsbroks/coco-annotator/wiki/Getting-Started#dedicated-servervps-setup

**Comment by walaceapolo** [comment]
Hey man, I'm new into linux/vps world so I'm very lost here. Where should I start? How can I download and install coco-annotator first? It's throught "docker pull jsbroks/coco-annotator"? Do I need to configure a DNS in the vps server? Any tutorial on how to get this working?

**Comment by jsbroks** [comment]
You can get an instance running by following the Getting Started section on the wiki. It explains what commands to us. You can then access it from the your servers at http://IP_ADDRESS:5000/. 

Recommend you look into using [ufw on centos](https://www.netweaver.uk/ufw-centos-7/) to protect from external access.

**Comment by walaceapolo** [comment]
Ok. In the vps server console I have to replace "git clone https://github.com/jsbroks/coco-annotator" by "docker pull jsbroks/coco-annotator" right?

**Comment by jsbroks** [comment]
No, please read though the the instructions on the wiki. Us git and docker-compose to run the server instance

**Comment by walaceapolo** [comment]
Right, I didn't has the git installed in the Centos. Now, I was able to clone the repo, but I couldn't install, got this error: "_Couldn't connect to Docker daemon at http+docker://localhost - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable._" Did you have the same error?

**Comment by jsbroks** [comment]
Please google around. Possible solution: https://github.com/docker/compose/issues/4181

**Comment by walaceapolo** [comment]
Hey man, I got it installed and running but I can't get the ui working, take a look a your inbox for the address.

**Comment by jsbroks** [comment]
I received no email. Using tools like: https://www.yougetsignal.com/tools/open-ports/ to check if the port is open

**Comment by walaceapolo** [comment]
Hi, I finally got it working. It's running on 8080 port.
**Thanks for everything Justin!**

**Comment by walaceapolo** [comment]
About the e-mail, I sent to jsbroks@gmail.com. Weird you didn't received. But thanks a lot man, you saved me!

**Comment by jsbroks** [comment]
Your running the development build if its on port 8080. It should on port 5000 for production

**Comment by jsbroks** [comment]
You on the development build I just checked. Please us production

**Comment by walaceapolo** [comment]
Yes, I've noticed after instalation. I'm going to try to install the production build! Thanks again!
