### ISSUE TITLE
Deleting an annotation in progress should remove current polygon

### ISSUE THREAD

**Issue by mveres01** [jsbroks/coco-annotator#19]
When you're in the middle of drawing a polygon and click "delete", the line stays visible as it waits for you to complete a polygon. 

Instead, the current polygon should disappear and be reset

**Comment by jsbroks** [comment]
A generic polygon delete has been implemented. I often find I'm annotating an image and realize I am on the wrong layer. Being able to transfer polygon selections between object layers fixes this issue.
