### ISSUE TITLE
typo when exporting dataset  (api/dataset/{id}/coco )

### ISSUE THREAD

**Issue by flo-dhalluin** [jsbroks/coco-annotator#191]
got the following stack. it seems a typo in the code. 

annotator_webclient | [2019-04-16 12:53:07 +0000] [11] [ERROR] Exception on /api/dataset/1/coco [GET]
annotator_webclient | Traceback (most recent call last):
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
annotator_webclient |     rv = self.dispatch_request()
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
annotator_webclient |     return self.view_functions[rule.endpoint](**req.view_args)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
annotator_webclient |     resp = resource(*args, **kwargs)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
annotator_webclient |     return self.dispatch_request(*args, **kwargs)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
annotator_webclient |     resp = meth(*args, **kwargs)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
annotator_webclient |     return func(*args, **kwargs)
annotator_webclient |   File "/workspace/webserver/api/datasets.py", line 452, in get
annotator_webclient |     return coco_util.get_dataseext_coco(dataset)
annotator_webclient | AttributeError: module 'webserver.util.coco_util' has no attribute 'get_dataseext_coco'

**Comment by flo-dhalluin** [comment]
Opened PR #192

**Comment by jsbroks** [comment]
Just would like to add a note here using the dropdown menu for exporting will be removed in the near future.
