### ISSUE TITLE
Cannot import images to new dataset

### ISSUE THREAD

**Issue by quangle2110** [jsbroks/coco-annotator#198]
Hi, I tried to import the images to my new dataset several times. I followed the exact steps on the wiki pages, the images still didn't appear when I put them in the folder under /datasets. I'm using windows 10 home with docker toolbox.

Thanks.

**Comment by jsbroks** [comment]
Under known issues, there is a section regarding [windows and file mounts](https://github.com/jsbroks/coco-annotator/wiki/Implementation#known-issues). The wiki hasn't been updated for a bit so try the scan button found in the datasets view first

**Comment by matthew-jurewicz** [comment]
It doesn't work for Mac either. I created a new data set I created a new data set and copied a bunch of images, but the file watcher only sees the first image. Scanning doesn't help.

**Comment by kevdagoat** [comment]
Make sure this line is the same as where your dataset folder is located in docker-compose.yml:

workers:
container_name: annotator_workers
image: jsbroks/coco-annotator:workers-stable
volumes:
- "./datasets:/datasets" <——- this one


https://github.com/jsbroks/coco-annotator/blob/fc5ab4c0ed2fc4578f4114d5f035d2b925f0c7b3/docker-compose.yml#L32
https://github.com/jsbroks/coco-annotator/blob/fc5ab4c0ed2fc4578f4114d5f035d2b925f0c7b3/docker-compose.yml#L32https://github.com/jsbroks/coco-annotator/blob/fc5ab4c0ed2fc4578f4114d5f035d2b925f0c7b3/docker-compose.yml#L32
