### ISSUE TITLE
Sometimes gets stuck "saving" during annotation

### ISSUE THREAD

**Issue by mveres01** [jsbroks/coco-annotator#20]
Not sure why this happens, but occasionally while annotating an image, the tool gets stuck on "saving data ...", which may prevent it from saving the most recent annotations

**Comment by mveres01** [comment]
To add: this seems to happen from the autosave feature. I haven't seen it happening from the manual save feature

**Comment by jsbroks** [comment]
@mveres01 If you experience this again, could you check the web console to see if any error messages are displayed?
