### ISSUE TITLE
display bbox

### ISSUE THREAD

**Issue by Apo11oAI** [jsbroks/coco-annotator#200]
I am performing cell labeling. 

Sometimes the color of the annotation is similar to  the cell. There may be a situation where a marker marks multiple cells. It's hard for me to find it.

Please add the function of displaying bbox so that I can check the dataset quickly.

thanks for your work,pretty awesome!

**Comment by jsbroks** [comment]
Could you please be more specific. You can change the colors of annotations

**Comment by Apo11oAI** [comment]
let me show you some example:
hard to find:
![pic0](https://user-images.githubusercontent.com/45376157/56884476-82002200-6a9c-11e9-9c44-0c4d4e6d1074.png)
easy to find:
![pic1](https://user-images.githubusercontent.com/45376157/56884526-a8be5880-6a9c-11e9-93da-c77c9676417c.png)

**Comment by jsbroks** [comment]
I understand you want to see bound box's but I don't understand how this will help make it 'easier to find'

**Comment by Apo11oAI** [comment]
emmmmm~time complexity may be a answer, it will be O(1) with bbox in this case. without bbox, to check according to the colors of annotations is almost same to Iterate through all the cells one by one.  

I am not sure if other users will encounter the same problem, but for me it is more intuitive and helpful to display bbox.

More specifically, the use case for displaying Bbox is to find mistakes that are supposed to be multiple annotations but are marked as a annotation, as the case i show above.

**Comment by jsbroks** [comment]
Time complexity of what? If 'finding' the annotation, how are you searching for it?
