### ISSUE TITLE
Username and dataset with annotations not available anymore

### ISSUE THREAD

**Issue by walaceapolo** [jsbroks/coco-annotator#205]
Hi, I'm kind desperate here.

I'm running C.A (10.2) in a VPS. Everything was working fine (since april 10) until this morning where we were going to continue annotating the images (2k to train, +300 to validate, separated in train/val folders), but out of nowhere just shows up to register a new user. And before creating a new user, I checked by sftp if the images was still in datasets folder and yes, it's. I checked the containers if something goes wrong, but it's all running. I checked if some volume was deleted by somehow, but i'ts all there. The server doesn't pass by any downtime since we've used the C.A (friday).

So, I'm wondering what happens and what or how can I recover the annotations of those +2k images that we've spent almost a month to get it done. If you want to access I can provide it in to your e-mail. Please, if we've to annotate all those images again, I'm a dead person :D

Best.

**Comment by jsbroks** [comment]
**You should always backup your data!** At the worst can restore the annotations from your latest export. 

I have contacted you privately for investigation.

**Comment by walaceapolo** [comment]
I've sent you an e-mail.
