### ISSUE TITLE
Saving current annotations should not reset the tool being used

### ISSUE THREAD

**Issue by mveres01** [jsbroks/coco-annotator#21]
When the "save" button is clicked (or ctrl+s is used), the tool currently resets from whatever it previously was to the default "pointer". 

This is a bit of an inconvenience for example when you've finished annotating one object in the image, and want to save the intermediate result. If you want to continue annotating the image, you need to re-enable the wand or polygon tool

**Comment by mveres01** [comment]
Edit: This seems to come from using the Ctrl+s macro, and not clicking the save on the left-hand side

**Comment by jsbroks** [comment]
Not exactly sure what was causing this issue.
I applied a quick fix that sets the active tool at the end of the `save` function to the one before. If this causes issues in later updates, this issue can be revisited.
