### ISSUE TITLE
Auto Re-Direct Pages

### ISSUE THREAD

**Issue by trinath503** [jsbroks/coco-annotator#214]
1. If a user is already logged in - even  open auth page can we redirect the user to the home page (since the user already loggedin)
2. If the non-loggin user types https://annotator.justinbrooks.ca/#/authkjndjfnksd can we redirect the user to https://annotator.justinbrooks.ca/#/auth (login page )

**Comment by jsbroks** [comment]
These redirects work fine for me on the test server. What browser are you using

**Comment by trinath503** [comment]
It's due to the browser version issue

**Comment by jsbroks** [comment]
@trinath503 What browser version issue?
