### ISSUE TITLE
I cant do anything

### ISSUE THREAD

**Issue by sshsurabhi** [jsbroks/coco-annotator#218]
Hello,

I've gone through all the step by process of docker installation and opening the coco-annotator. But I cannot able to import my own images to annotate. What should I do? I tried to move my images into dataset folder also which I could not able to do so. 

I need to annotate my own images. Please help me with patience?

Thanks in advance.

**Comment by jsbroks** [comment]
Please provide more details. Including but not limited to:
Operating system
A step by step guide on how you are running the annotator

The more detail the better

**Comment by ilyes-hamrouni** [comment]
I have the same issue, when you go to /datasets, and click on import nothing happens, i peeked at the code in vuejs and there is no function to import button

**Comment by jsbroks** [comment]
You should not be using the dropdown menu import function found at /datasets. It is the old way and depreciated.

Instead you should is the import buttons found on the view of a dataset. /dataset/<number>

**Comment by zhengrenjiechn** [comment]
Excuse me ,I meet the same issue,the import button has no response but the creat button works,have you solve this? thank you !
