### ISSUE TITLE
Container Name for Windows Fix

### ISSUE THREAD

**Issue by cvKDean** [jsbroks/coco-annotator#219]
Good day, I am trying to run the annotator using Windows.

I found these steps in an earlier issue so that datasets can be created in Windows: https://github.com/jsbroks/coco-annotator/issues/44#issuecomment-445509053

However, the steps mentioned a docker container named `annotator-flask`, while the containers that are listed when I ran `docker-compose up` were named `annotator_mongodb` and `coco-annotator_flask_1`. Which one of these containers should I use? Thank you.

**Comment by jsbroks** [comment]
You need both containers

**Comment by cvKDean** [comment]
Sorry for the late response. Does this mean I will have to do steps 3 and 4 on both containers, which are:

3. Create an interactive bash shell on the container (annotator must be running).
`$ docker exec -it CONTAINER_NAME bash`
4. Move the folders or images into the proper datasets folder from within the interactive bash shell terminal
`$ mv /data/datasets/temp/some_image_folder /data/dataset/SomeDataset/`

**Comment by jsbroks** [comment]
Only on the flask container (coco-annotator_flask_1)

**Comment by rajatongit** [comment]
Hey, I'm not an advanced user of Docker myself. I have these containers available. 
![image](https://user-images.githubusercontent.com/22437185/61221110-0e26fa80-a718-11e9-81c9-30acd051a541.png)
No such coco-annotator_flask_1 container available. 
I am using windows7 with docker-toolbox.

**Comment by jsbroks** [comment]
Yes you should, I will update the docs.
