### ISSUE TITLE
"Delete Dataset" should have a confirmation box

### ISSUE THREAD

**Issue by mveres01** [jsbroks/coco-annotator#22]
Holy cow am I happy there's an "undo" feature.

There should definitely be an "Are you sure?" button before even the soft delete

**Comment by jsbroks** [comment]
A confirmation will be added to full deletion but not partial delete.

**Comment by mveres01** [comment]
I can understand the reasoning that it's not a "full" delete, but I'm willing to bet as the tool gets adopted a lot of issues are going to be opened up about accidentally deleting their dataset
