### ISSUE TITLE
demo account not working

### ISSUE THREAD

**Issue by tfriedel** [jsbroks/coco-annotator#221]
I can't login with "admin / password".

**Comment by jsbroks** [comment]
Someone probably changed the password  I'll reset it in a few hours.

Thanks

**Comment by lukemelas** [comment]
The demo is still not working, at least for me.

**Comment by lolmino** [comment]
25.07.2019 still does not work with following:
username=admin
password=password

**Comment by jsbroks** [comment]
I really have to set up some type of automated wipe to happen everyday.

For the time being you can register an account
