### ISSUE TITLE
DEXTR tool is not worked

### ISSUE THREAD

**Issue by hao6699** [jsbroks/coco-annotator#225]
I am using the production build mode, but it seems that the DEXTR tool is not worked. 
Here is the problem:
If I choose the DEXTR tool button, I can label three points in the picture. However, when I attempt to label the fourth point, as long as I click the left mouse button, all points disappear.
So, does the production build mode supports the DEXTR tool, if does, how can I use it?

**Comment by jsbroks** [comment]
Please reference to #176  for a guide on how to setup DEXTR
