### ISSUE TITLE
Migration from local mongo to atlas mongo

### ISSUE THREAD

**Issue by trinath503** [jsbroks/coco-annotator#227]
Anyone know how to move mongo from local to online.
1. Remove connection in the docker-compose file
2. Change mongo connection in the backend config file

After doing these changes getting the error: 
![Screenshot from 2019-07-15 13-08-35](https://user-images.githubusercontent.com/19545163/61365391-49a2ff80-a8a5-11e9-802e-cc2a0002f2d6.png)

**Comment by EMCP** [comment]
is the ATLAS cluster setup to accept connections?  seems to point to a refused connection
