### ISSUE TITLE
Ability to pan while zoomed in

### ISSUE THREAD

**Issue by mveres01** [jsbroks/coco-annotator#23]
When zoomed in on an object while annotating, sometimes the whole object is not in view. Thus, in order to annotate the full object, we're currently required to re-center it, and then zoom in again if needed. 

An option to pan (e.g. by pressing the wheel button) would be helpful to avoid this.

(Come to think of it, a config file for "keybinds" could also be really useful)

**Comment by jsbroks** [comment]
`Shift + Mousewheel` - pan left and right
`Ctrl + Mousewheel` - pan up and down

**Comment by mveres01** [comment]
Sweet, thanks!
