### ISSUE TITLE
The development build error?

### ISSUE THREAD

**Issue by hao6699** [jsbroks/coco-annotator#230]
When I build with the development build, I use the command:
`docker-compose -f docker-compose.dev.yml up --build`
and it says:
**Step 7/10 : COPY ./.git /workspace/.git
ERROR: Service 'flask' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder662668808/.git: no such file or directory**
When I try to comment `COPY ./.git /workspace/.git` in the dockerfile,
then I open the  `http://localhost:5000/`, it turns out a blank page.
Furthermore, I open the `http://localhost:8080/`, it shows the "login" page, but I can not register any name, and so I can not be authorized to login.

**Comment by jsbroks** [comment]
Did you clone the repo using git?

**Comment by WarrentLee** [comment]
You should use git clone command, so that the hidding directory '.git' will be downloaded. Don't use 'Download ZIP'.
