### ISSUE TITLE
Set up a server with an AWS VM.

### ISSUE THREAD

**Issue by SergioPesquera** [jsbroks/coco-annotator#231]
Hi!

I'm trying to set up a VM in AWS with coco-annotator so I can enter the interface through my domain, and annotate from any place I want.

I've been trying to follow instructions from #185 and from https://github.com/jsbroks/coco-annotator/wiki/Getting-Started#dedicated-servervps-setup , and I  can't get it working.

1st I don't know where to put the lines of "code" that you say we need to use to set up linuxserver/letsencrypt, i've try to create a separate docker-compose.yml, and to put them on same docker-compose.yml as coco-annotator is. (I think most of my problems come from that I don't really know how docker works (I'm sorry about that)).

2nd I don't find either where the directorie that you mention of nginx is, or how am i supossed to set it up...

I see that on #185 the guy figured it out, but I don't see how, cause he didn't tell.

I hope that you can help me, thank u in advance.

**Comment by jsbroks** [comment]
Do you own a domain name for this? is the domain name being used elsewhere?

**Comment by SergioPesquera** [comment]
Yes, I do own a domain, yes the domain is being used somewhere else but I've generated an "A" type register for the DNS with a subdomain. 

I've make it working with the AWS Elastic IP, but whenever i create a user inside annotator, and i get into with the credencials, it enters the annotator UI, and then comes back like 3 seconds later to the register page... I don't know why :/

**Comment by chitraa** [comment]
Hi I have run into a similar issue. Which container is responsible for starting nginx? Or do need I start nginx myself from the VM itself? 
I added the example `/config/nginx/site-confs/default` file after letsencrypt container is created.  I get an error from the letsencrypt container when I start this container again for validation (with nginx running on the vm)

> letsencrypt    | Problem binding to port 80: Could not bind to IPv4 or IPv6.
> letsencrypt    | ERROR: Cert does not exist! Please see the validation error above. The issue may be due to incorrect dns or port forwarding settings. Please fix your settings and recreate the container.


@jsbroks as you suggested, I checked https://www.yougetsignal.com/tools/open-ports/ and my http port 80 is open. 
Is there something obvious that I am missing out?

**Comment by jsbroks** [comment]
Check out: https://community.letsencrypt.org/t/problem-binding-to-port-80-with-standalone/50850

The letsencrypt container will also run nigix for you

**Comment by chitraa** [comment]
Thanks @jsbroks ! I deleted the config and recreated all containers. My ssl certificates were created successfully. Nginx is running successfully. :)
However, my ssl (https) is still not up. I'll post some curl output to help guide me where I might be going wrong:

`curl localhost:5000` returns the right hosted webpage from coco-annotator.
`curl localhost:80` or `curl localhost` returns 
> <html>
> <head><title>301 Moved Permanently</title></head>
> <body>
> <center><h1>301 Moved Permanently</h1></center>
> <hr><center>nginx/1.16.1</center>
> </body>
> </html>

And finally `curl localhost:443` returns
> <html>
> <head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
> <body>
> <center><h1>400 Bad Request</h1></center>
> <center>The plain HTTP request was sent to HTTPS port</center>
> <hr><center>nginx/1.16.1</center>
> </body>
> </html>

I edited the `/config/nginx/site-confs/default` to the one example you have provided. My domain name is of the form foo.bar.xyz.com. I edited the server_name to be the same.
I had also edited the letsencrypt docker-compose script to include my url i.e. - URL=foo.bar.xyz.com without subdomains. 

https://www.yougetsignal.com/tools/open-ports/ shows port 80 is open and 443 is closed to the outside world.
I am quite new to nginx and docker, hope this can help you point me in the right direction?

**Comment by chitraa** [comment]
I finally managed to get everything running. Tons of firewalls were blocking https, my bad! I had to allow 443 using ufw, apart from enabling these from a cloud service's virtual network.

**Comment by mgarbade** [comment]
@SergioPesquera Could you share a little bit, how you managed to launch the coco-annotator on AWS? 
I found a general tutorial to run a free experimental AWS server [here], however it's not working yet (https://www.youtube.com/watch?v=ubCNZRNjhyo))

1) What "product" did you choose? ("EC2" (virtual machine)? "Elatic Beanstalk" (web application)?
2) What pre-installation did you choose? ("Docker - single instance"?)
3) How did you tell AWS, how to launch the command for the coco-annotator? (login via ssh and run the command manually? or is there some pre-configuration that enters the respective source folder automatically and runs `docker-compose up` on startup?)

4) Quote: `"1st I don't know where to put the lines of "code" that you say we need to use to set up linuxserver/letsencrypt, i've try to create a separate docker-compose.yml, and to put them on same docker-compose.yml as coco-annotator is. (I think most of my problems come from that I don't really know how docker works (I'm sorry about that))."`
--> What was the answer to your question. Where did you put the respective lines?

**Comment by mgarbade** [comment]
Here are some answers to my above questions:

1. Choose EC2 
2. Choose t2.micro (free tier eligible) for example with Ubuntu 18.04
3. Login to your ec2 virtual machine instance via ssh and run manually install the coco-annotator
4. Edit the file  `docker-compose.yml` by adding a few lines under "services" specifying the IP to your AWS machine, time zone as well as user and group id corresponding to your user on that machine

```
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    network_mode: host
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config:/config
    environment:
      # Domain name
      - URL=ec2-34-34-326-297.eu-west-1.compute.amazonaws.com      <-- edit
      - TZ=Etc/UTC      <-- edit if necessary
      - PGID=1000      <-- edit if necessary
      - PUID=1000      <-- edit if necessary
      # Subdomain to encrypt
      - Subdomains=www,annotator
    cap_add:
      - NET_ADMIN
  webserver:
    image: jsbroks/coco-annotator:webserver-stable
   [...]
```
5. make the  IP-Adress to your ec2 instance permanent ([click](https://www.youtube.com/watch?v=mgfpduy5ZAo))
6. make your ec2 instance accessible via the browser ([click](https://www.youtube.com/watch?v=ukdTGVVcqE0))

**Comment by mgarbade** [comment]
That said, I still haven't got the "https-login" working yet and get a bunch of error messages on launch: 

```
Attaching to letsencrypt, annotator_message_q, annotator_mongodb, annotator_workers, annotator_webclient
[36mletsencrypt    |[0m [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[36mletsencrypt    |[0m [s6-init] ensuring user provided files have correct perms...exited 0.
[36mletsencrypt    |[0m [fix-attrs.d] applying ownership & permissions fixes...
[36mletsencrypt    |[0m [fix-attrs.d] done.
[36mletsencrypt    |[0m [cont-init.d] executing container initialization scripts...
[36mletsencrypt    |[0m [cont-init.d] 10-adduser: executing... 
[36mletsencrypt    |[0m usermod: no changes
[36mletsencrypt    |[0m 
[36mletsencrypt    |[0m -------------------------------------
[36mletsencrypt    |[0m           _         ()
[36mletsencrypt    |[0m          | |  ___   _    __
[36mletsencrypt    |[0m          | | / __| | |  /  \ 
[36mletsencrypt    |[0m          | | \__ \ | | | () |
[36mletsencrypt    |[0m          |_| |___/ |_|  \__/
[36mletsencrypt    |[0m 
[36mletsencrypt    |[0m 
[36mletsencrypt    |[0m Brought to you by linuxserver.io
[36mletsencrypt    |[0m We gratefully accept donations at:
[36mletsencrypt    |[0m https://www.linuxserver.io/donate/
[36mletsencrypt    |[0m -------------------------------------
[36mletsencrypt    |[0m GID/UID
[36mletsencrypt    |[0m -------------------------------------
[36mletsencrypt    |[0m 
[36mletsencrypt    |[0m User uid:    1000
[36mletsencrypt    |[0m User gid:    1000
[36mletsencrypt    |[0m -------------------------------------
[36mletsencrypt    |[0m 
[36mletsencrypt    |[0m [cont-init.d] 10-adduser: exited 0.
[36mletsencrypt    |[0m [cont-init.d] 20-config: executing... 
[36mletsencrypt    |[0m [cont-init.d] 20-config: exited 0.
[36mletsencrypt    |[0m [cont-init.d] 30-keygen: executing... 
[36mletsencrypt    |[0m using keys found in /config/keys
[36mletsencrypt    |[0m [cont-init.d] 30-keygen: exited 0.
[36mletsencrypt    |[0m [cont-init.d] 50-config: executing... 
[36mletsencrypt    |[0m Variables set:
[36mletsencrypt    |[0m PUID=1000
[36mletsencrypt    |[0m PGID=1000
[36mletsencrypt    |[0m TZ=Etc/UTC
[36mletsencrypt    |[0m URL=ec2-34-34-326-297.eu-west-1.compute.amazonaws.com
[36mletsencrypt    |[0m SUBDOMAINS=
[36mletsencrypt    |[0m EXTRA_DOMAINS=
[36mletsencrypt    |[0m ONLY_SUBDOMAINS=false
[36mletsencrypt    |[0m DHLEVEL=2048
[36mletsencrypt    |[0m VALIDATION=
[36mletsencrypt    |[0m DNSPLUGIN=
[36mletsencrypt    |[0m EMAIL=
[36mletsencrypt    |[0m STAGING=
[36mletsencrypt    |[0m 
[36mletsencrypt    |[0m VALIDATION parameter not set; setting it to http
[36mletsencrypt    |[0m 2048 bit DH parameters present
[36mletsencrypt    |[0m No subdomains defined
[36mletsencrypt    |[0m No e-mail address entered or address invalid
[36mletsencrypt    |[0m http validation is selected
[36mletsencrypt    |[0m Generating new certificate
[36mletsencrypt    |[0m Saving debug log to /var/log/letsencrypt/letsencrypt.log
[36mletsencrypt    |[0m Plugins selected: Authenticator standalone, Installer None
[36mletsencrypt    |[0m Obtaining a new certificate
[32mannotator_mongodb |[0m 2019-10-08T16:15:50.830+0000 I STORAGE  [main] Max cache overflow file size custom option: 0
[35mannotator_workers |[0m fatal: Not a git repository (or any of the parent directories): .git
[31mannotator_webclient |[0m [2019-10-08 16:15:57 +0000] [6] [DEBUG] Current configuration:
[31mannotator_webclient |[0m   config: webserver/gunicorn_config.py
[31mannotator_webclient |[0m   bind: ['0.0.0.0:5000']
[...]
[31mannotator_webclient |[0m [2019-10-08 16:15:57 +0000] [6] [DEBUG] 1 workers
[35mannotator_workers |[0m /usr/local/lib/python3.6/site-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
[35mannotator_workers |[0m absolutely not recommended!
[35mannotator_workers |[0m 
[35mannotator_workers |[0m Please specify a different user using the --uid option.
[35mannotator_workers |[0m 
[35mannotator_workers |[0m User information: uid=0 euid=0 gid=0 egid=0
[35mannotator_workers |[0m 
[35mannotator_workers |[0m   uid=uid, euid=euid, gid=gid, egid=egid,
[35mannotator_workers |[0m [2019-10-08 16:15:59,182: ERROR/MainProcess] consumer: Cannot connect to amqp://user:**@messageq:5672//: [Errno 111] Connection refused.
[35mannotator_workers |[0m Trying again in 2.00 seconds...
[31mannotator_webclient |[0m Traceback (most recent call last):
[31mannotator_webclient |[0m   File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 141, in _connect
[31mannotator_webclient |[0m     host, port, family, socket.SOCK_STREAM, SOL_TCP)
[31mannotator_webclient |[0m   File "/usr/local/lib/python3.6/site-packages/eventlet/support/greendns.py", line 537, in getaddrinfo
[31mannotator_webclient |[0m     raise socket.gaierror(socket.EAI_NONAME, 'No address found')
[31mannotator_webclient |[0m socket.gaierror: [Errno -2] No address found
[31mannotator_webclient |[0m 
[31mannotator_webclient |[0m During handling of the above exception, another exception occurred:
[31mannotator_webclient |[0m 
[31mannotator_webclient |[0m Traceback (most recent call last):
[31mannotator_webclient |[0m   File "/usr/local/lib/python3.6/site-packages/kombu/utils/functional.py", line 341, in retry_over_time
[31mannotator_webclient |[0m     return fun(*args, **kwargs)
[31mannotator_webclient |[0m   File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 275, in connect
[31mannotator_webclient |[0m     return self.connection
[31mannotator_webclient |[0m   File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 823, in connection
[31mannotator_webclient |[0m     self._connection = self._establish_connection()
[31mannotator_webclient |[0m   File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 778, in _establish_connection
[31mannotator_webclient |[0m     conn = self.transport.establish_connection()
[31mannotator_webclient |[0m   File "/usr/local/lib/python3.6/site-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
[31mannotator_webclient |[0m     conn.connect()
[31mannotator_webclient |[0m   File "/usr/local/lib/python3.6/site-packages/amqp/connection.py", line 307, in connect
[31mannotator_webclient |[0m     self.transport.connect()
[31mannotator_webclient |[0m   File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 81, in connect
[31mannotator_webclient |[0m     self._connect(self.host, self.port, self.connect_timeout)
[31mannotator_webclient |[0m   File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 152, in _connect
[31mannotator_webclient |[0m     "failed to resolve broker hostname"))
[31mannotator_webclient |[0m   File "/usr/local/lib/python3.6/site-packages/amqp/transport.py", line 165, in _connect
[31mannotator_webclient |[0m     self.sock.connect(sa)
[31mannotator_webclient |[0m   File "/usr/local/lib/python3.6/site-packages/eventlet/greenio/base.py", line 265, in connect
[31mannotator_webclient |[0m     socket_checkerr(fd)
[31mannotator_webclient |[0m   File "/usr/local/lib/python3.6/site-packages/eventlet/greenio/base.py", line 51, in socket_checkerr
[31mannotator_webclient |[0m     raise socket.error(err, errno.errorcode[err])
[31mannotator_webclient |[0m ConnectionRefusedError: [Errno 111] ECONNREFUSED
[...]
```

Will continue looking into this tomorrow...

**Comment by jsbroks** [comment]
Probably something to do with the network as it looks like the services can't talk to each other

**Comment by mgarbade** [comment]
Poblem might be, that letsencrypt is not accepting ec2 amazon domain names as suggested [here](https://community.letsencrypt.org/t/policy-forbids-issuing-for-name-on-amazon-ec2-domain/12692/2)

**Comment by mgarbade** [comment]
Problem solved: 
I had the domain server configured wrong. 
Instead of URL forwarding I needed 
- to create a "hosted zone" using the AWS "Route 53"-Service
- "Create Record Set"  -> Name: "www.yourWebdomain.com" Value: "yourAwsEc2IpAddress"
- note the nameservers provided by Amazon (ns-*.awsdns-20.*) and enter them as custom nameservers on the config page of your domain provider
- now the communication between nginx, letsencrypt and your AWS ec2 instance should be working
