### ISSUE TITLE
Make other users Admin

### ISSUE THREAD

**Issue by GeorgeSeif** [jsbroks/coco-annotator#232]
Is there away to make multiple users admins? Currently, we have 1 admin and many regular users but would like to have 2 different admin accounts.

**Comment by jsbroks** [comment]
1. Login in as the admin user
2. Go to the Admin tab found in the navbar
3. Use the `Create User` button and make sure to select the admin checkbox

Note: If the user already exists you can delete them and re-add them as an admin. The user can then login and change there password

If you don't want to re-create their accounts, you can manipulate the databased and set is_admin to true in the users collection. You can use mongo-compass or the mono engine python library found in the `backend/database`

**Comment by GeorgeSeif** [comment]
Thanks @jsbroks! It worked. Great repository :)
