### ISSUE TITLE
Kubernetes deploymeny fails "OSError("inotify watch limit reached")"

### ISSUE THREAD

**Issue by jeroenroodnat** [jsbroks/coco-annotator#234]
I have been working on getting coco-annotator to run on Kuberneters. The webserver container fails constantly with "OSError("inotify watch limit reached")"

Looking at the code this is caused by the observer watching folders. This cannot be solved on Kubernetes unless you fix the underlying file watch limit which is at the node level in the cluster.

**Comment by jsbroks** [comment]
You can disable the [File Watcher](https://github.com/jsbroks/coco-annotator/blob/15328a2b2adc1deea3b6787454c0fa7e551fae12/backend/config/config.py#L16) using environment variables

**Comment by jeroenroodnat** [comment]
At tried setting the FILE_WATCH environment variable to false the the deployment yaml file in Kubernetes:

        env:
        - name: FILE_WATCHER
          value: "FALSE"

This results in the same error on the webserver container. The environment variables is set in the container but not recognized by the code for some reason. 

Workaround is to not set the FILE_WATCHER env at all in the yaml config and then the webserver boots as expected.
