### ISSUE TITLE
annotator_mongodb | Error parsing command line: unrecognised option '--smallfiles'

### ISSUE THREAD

**Issue by Kunaldargan** [jsbroks/coco-annotator#238]

**Comment by chitraa** [comment]
Hey remove `--smallfiles` from `docker-compose.yml`. You should be able to spin the container annotator_mongodb up. I am not sure about the repurcussions, the current image maybe built with a different mongodb version. 
[Here](https://stackoverflow.com/questions/11613769/mongo-db-smallfiles-switch-drawbacks) are some smallfiles drawbacks though.

**Comment by ghostrider77** [comment]
In Mongo 4.2 the `--smallfiles` mongod command line option is removed and I assume that the mongo4 image on dockerhub now refers to this version. Either specifiy a lower mongo4.x version in the `docker-compose` files or remove the `--smallfiles` flag (although the latter solution still resulted in some tracebacks in the console).

**Comment by jsbroks** [comment]
Docker-compose has veeb updated with the appropriate version

**Comment by valek** [comment]
@jsbroks : 
I believe this should also be done in docker-compose.build.yml and ocker-compose.dev.yml !

**Comment by jsbroks** [comment]
They change has been made to all dockerfiles
