### ISSUE TITLE
how to unimport coco annotations (and where are imported annotations stored?)

### ISSUE THREAD

**Issue by rbavery** [jsbroks/coco-annotator#245]
I imported some messed up annotations that I'd like to remove but it's proving difficult. Here's what I've tried:

![Selection_050](https://user-images.githubusercontent.com/22258697/64315464-f5440400-cf66-11e9-94fb-565ba32dc107.png)

1. deleting the coco-annotator directory, re-cloning
2. purging the docker images and remaking the annotator with `docker system prune -a`
3. looking in my mounted datasets folder and home directory with `ls -a` to see if the annotations are stored in some hidden directory or somewhere in the repo
4. using the reset metadata button in settings (this doesn't seem to do anything)
5. Importing my new annotations to see if they would replace the old ones, they didn't get imported.

I've missed something because none of these options has turned up anything, the annotations I imported a few days ago are still there and I can't delete them. Any pointers are appreciated!

**Comment by jsbroks** [comment]
For removing all data from the database: https://github.com/jsbroks/coco-annotator/wiki/Implementation#database-volume

This will create a fresh wipe of the annotator.

Other than that you can import the database library and use the mongoengine models to delete large amounts of data.

**Comment by rbavery** [comment]
Ah awesome, thanks a bunch for the quick reply.

**Comment by rbavery** [comment]
Just a heads up, deleting just that volume didn't work for me, my annotations remained. but I fixed it by deleting all containers and then all volumes with `docker volume prune`. This wiki helped https://github.com/Radu-Raicea/Dockerized-Flask/wiki/%5BDocker%5D-Remove-all-Docker-volumes-to-delete-the-database

**Comment by jsbroks** [comment]
@rbavery can we close this?
