### ISSUE TITLE
Where is the BBox tool in v0.10.5?

### ISSUE THREAD

**Issue by ZiliPeng** [jsbroks/coco-annotator#246]
I find a BBox tool for task of detection in your annotator demo, but I cannot get this tool from my local deployment at the version 0.10.5.

**Comment by jsbroks** [comment]
Switch the docker images to `latest` instead of `stable`

**Comment by ZiliPeng** [comment]
> Switch the docker images to `latest` instead of `stable`

Thanks. Got it.
