### ISSUE TITLE
Unexpected Error while running the app

### ISSUE THREAD

**Issue by trinath503** [jsbroks/coco-annotator#247]
command: sudo docker-compose -f docker-compose.build.yml up --build,
its not happening  while  using docker-compose.dev.yml
![Screenshot from 2019-09-13 13-57-20](https://user-images.githubusercontent.com/19545163/64848838-bb8e8f80-d62f-11e9-9f3f-c9acdb6047d6.png)

**Comment by jsbroks** [comment]
Probably need to update webpack, https://github.com/vuejs/vue-cli/issues/4572

**Comment by trinath503** [comment]
No, after clearing the node module cache it worked
