### ISSUE TITLE
Latest build does not show images in annotator

### ISSUE THREAD

**Issue by mveres01** [jsbroks/coco-annotator#25]
A fresh install of the annotator no longer seems to show any images in the annotator area (e.g. http://localhost:5000/annotate/691)

I can create a new dataset and images appear in the main dataset directory, but are not visible once it gets clicked to begin annotating

**Comment by jsbroks** [comment]
Does the web console show any errors?

**Comment by mveres01** [comment]
Just to update from our offline discussion if it happens again:

* Chrome seems to work as intended, but firefox no longer seems to work

I'll close for now, and we can re-open if it comes up again. Thanks for looking into it!
