### ISSUE TITLE
Want to move the created dataset to another PC

### ISSUE THREAD

**Issue by tatoyu** [jsbroks/coco-annotator#251]
I want to move a dataset created with coco annotator on MacOS to Linux PC.
Can you tell me how to move the dataset to another PC?

**Comment by jsbroks** [comment]
You'll need to do 2 things:

1. Copy your datasets folder to the new system
2. Copy the docker database volume to the new system

**Comment by mgarbade** [comment]
@jsbroks Could you explain how to perform step 2.

**Comment by jsbroks** [comment]
Im not sure, you can find resources online

**Comment by mgarbade** [comment]
[This command](https://stackoverflow.com/a/42975574/2191652) is doing the trick: 

On the target machine:
- shut down docker 
- erase all docker images 
- erase all docker volumes

On the source machine:
`docker run --rm -v cocoannotator_mongodb_data:/from alpine ash -c "cd /from ; tar -cf - . " | ssh -i "~/Downloads/myAwsKey.pem" ubuntu@ec2-32-31-215-232.eu-west-1.compute.amazonaws.com 'docker run --rm -i -v cocoannotator_mongodb_data:/to alpine ash -c "cd /to ; tar -xpvf - "'`

then re-clone the coco-annotator repository and restart

**Comment by jsbroks** [comment]
Thanks for sharing!
