### ISSUE TITLE
how to install in my local windows 10?

### ISSUE THREAD

**Issue by sezan92** [jsbroks/coco-annotator#253]

**Comment by kunalmunjal** [comment]
I would highly suggest NOT TO install it on windows. Use Ubuntu/Linux to install coco.

The easy way on Ubuntu 18.04 -

sudo apt-get update
sudo apt-get remove docker docker-engine docker.io
sudo apt install docker.io
sudo systemctl start docker
sudo systemctl enable docker
git clone https://github.com/jsbroks/coco-annotator.git
cd coco-annotator
sudo docker-compose up

## Now let terminal boot the docker image. Once this comes -
celery@******* Ready

on terminal,

Go to Browser
http://localhost/5000

**Comment by sezan92** [comment]
but I have to install in windows ,

**Comment by kunalmunjal** [comment]
How about Virtual Image?

Otherwise, you have to download Docker and follow the instructions given in the docker documentation.

**Comment by kevdagoat** [comment]
Works fine on windows?!

Install Docker desktop and Git for windows

**Comment by menglunl611** [comment]
> 
> 
> but I have to install in windows

You can achieve that following my instructions below:
1. Download Docker desktop from https://www.docker.com/products/docker-desktop
2.1. After reboot, Docker may show you some errors and ask you to update packages following the link below: https://docs.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package
2.2. During the installation, you may be required to install the executable wsl_update_x64.msi from https://docs.microsoft.com/en-us/windows/terminal/get-started
2.3. Install Ubuntu 18.04 from Microsoft Store
2.4. Install Windows Terminal from https://docs.microsoft.com/en-us/windows/terminal/get-started
3.1. After all the packages above all installed, open the windows terminal and launch the Ubuntu 18.04 kernel
3.2. Type "docker version" and then "docker-compose version" to check if the correct Docker engine is installed successfully
3.3 Type "docker run hello-world" to verify if your local machine can run a basic docker application without fail
4. Download Git from https://git-scm.com/downloads
5.1. Launch Ubuntu 18.04 from the windows terminal, then type "git clone https://github.com/jsbroks/coco-annotator.git"
5.2. Type "cd coco-annotator" and then type "docker-compose up"
6. Open your web browser and type the address "http://localhost:5000"
