### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by kunalmunjal** [jsbroks/coco-annotator#254]
I want to change the output json file which the annotator provides. 
I have tried editing the backend/workers/tasks/data.py file.
and also the backend/webserver/util/coco_util.py file 

I pruned the docker image and restarted it but to no effect. I want some insight as to whether I am editing the right file(s)?
If not, which file needs to be edited?

**Comment by jsbroks** [comment]
You are looking at the correct files. Are you running the production docker image or the dev build?

**Comment by kunalmunjal** [comment]
I am running the production docker image using
sudo docker-compose up

**Comment by jsbroks** [comment]
That pulls the docker image from dockerhub. Therefore any changes you make locally will not be applied.

[Development Build](https://github.com/jsbroks/coco-annotator/wiki/Getting-Started#Development-Build)

**Comment by kunalmunjal** [comment]
Ohh I see, thanks! That explains a lot. Also, both the files which I mentioned need to be edited or will just one do?
Because data.py contains the export_annotations method

**Comment by jsbroks** [comment]
`data.py` should be the function. What functionally do you plan on adding?

**Comment by kunalmunjal** [comment]
Not exactly adding a functionality but changing just the output of the schema of the json file. I thought coco_util file would be needing editing since it had the functions of getting coco from image/dataset and was writing to the coco dictionary.

**Comment by jsbroks** [comment]
Exporting using the rest api you will need to modify the [coco_utils](https://github.com/jsbroks/coco-annotator/blob/6f14d65142fa1007cecb03b290ccc01f9c26e6e3/backend/webserver/api/datasets.py#L477). If exporting using workers then data.py

If you are adding additions that may help others, please consider creating a pull request

**Comment by kunalmunjal** [comment]
Ohh! perfect. I will do that! I highly doubt it would help anyone since it is just a schema change.
Also, I might try to go through some issues! I am new to object detection!

**Comment by kunalmunjal** [comment]
Hey,
So I tried using the development build. It gave -

App running at  http://localhost:8080/

and when I open it up, it doesn't let me login/register/Do anything
