### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by kunalmunjal** [jsbroks/coco-annotator#255]
Hey,

I was trying to import an image of size 1.5 GB image on the dataset on coco but was unable to do so. It always threw a warning that it couldn't read the image.

**Comment by jsbroks** [comment]
Could you provide the warning?

**Comment by kunalmunjal** [comment]
[02-10-2019 13:57:55] [INFO] Created 0 new image(s)

[02-10-2019 13:57:55] [WARNING] Could not read /datasets/test2/******************.bmp

[02-10-2019 13:57:55] [INFO] Scanning /datasets/test2/

**Comment by jsbroks** [comment]
Any error provided in the console

**Comment by kunalmunjal** [comment]
Nope

**Comment by jsbroks** [comment]
Have you successful scan other bmp files?

You should compress the image as 1.5GB is very large. 
There is no support for such large files.

**Comment by kunalmunjal** [comment]
Yup! I could scan smaller files < 100 MB successfully
