### ISSUE TITLE
Development Build issue.

### ISSUE THREAD

**Issue by kunalmunjal** [jsbroks/coco-annotator#257]
Hey,
So I tried using the development build. It gave -

App running at http://localhost:8080/

and when I open it up, it doesn't let me login/register/Do anything

**Comment by jsbroks** [comment]
Strange, any errors in the terminal output?

**Comment by kunalmunjal** [comment]
None, no errors

**Comment by kunalmunjal** [comment]
Gives this though:

annotator_client | Proxy error: Could not proxy request /?EIO=3&transport=polling&t=MrpoDst from localhost:8080 to http://webserver:5000/socket.io.
annotator_client | See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ENOTFOUND).

**Comment by jsbroks** [comment]
Not sure the cause. Maybe do  `docker system prune -a` and re pull the server images

**Comment by kunalmunjal** [comment]
Yup, tried that as well. Didn't work

**Comment by kunalmunjal** [comment]
Is it working on your machine?

**Comment by jsbroks** [comment]
I havent run the dev build since last merge. Ill take a look

**Comment by kunalmunjal** [comment]
Thank you! Please let me know what's wrong. As far as I can tell, it is a JS issue on the front end. I looked at the Vue code. But let me know please.

**Comment by jsbroks** [comment]
@kunalmunjal Did you figure out what the issue is?

**Comment by kunalmunjal** [comment]
Yep! It was apparently a firewall issue in my firm's laptop so the ports were unable to communicate with each other.

**Comment by geoffreysteven** [comment]
What OS where you using on your laptop and how did you open the ports? I've disabled the firewall on my side, it did not solve the problem.

**Comment by sebo313** [comment]
Hi @kunalmunjal @geoffreysteven , i have a similar issue when calling my own api. I get following error:

```
annotator_client | Proxy error: Could not proxy request /model/openpose from localhost:8080 to http://webserver:5000/api/.
annotator_client | See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
annotator_client | 
annotator_message_q | 2020-04-03 11:23:45.806 [warning] <0.2106.0> closing AMQP connection <0.2106.0> (172.19.0.5:41996 -> 172.19.0.2:5672, vhost: '/', user: 'user'):
annotator_message_q | client unexpectedly closed TCP connection
annotator_webserver | [2020-04-03 11:23:45 +0000] [602] [INFO] Booting worker with pid: 602
annotator_message_q | 2020-04-03 11:23:45.802 [warning] <0.2086.0> closing AMQP connection <0.2086.0> (172.19.0.5:41924 -> 172.19.0.2:5672, vhost: '/', user: 'user'):
annotator_message_q | client unexpectedly closed TCP connection
```

I deactivated my firewall (macOS), but it is still the same error. Any idea how to solve this?
