### ISSUE TITLE
Loading font-awesome.css from cdn prevents offline usage

### ISSUE THREAD

**Issue by stefanvangastel** [jsbroks/coco-annotator#258]
I want to use this awesome tool in an offline, on-premise network. Almost everything works as expected except for some of the buttons, I guess this can be related to:

https://github.com/jsbroks/coco-annotator/blob/master/client/public/index.html#L9

Where the css is loaded from a public cdn we cannot access.

Would it be possible to include the css? So the entire tool is completely offline?

**Comment by jsbroks** [comment]
1. Download [font-awesome.min.css 4.7.2](https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css)
2. Place the file in the client/public directory 
3. Change the ref to `href="<%= BASE_URL %>front-awesome.min.css"`

**Comment by ykk648** [comment]
I have changed the file, but the deplyed docker image may not changed, the web html still ref cloudflare which I can't reach.
