### ISSUE TITLE
Best way to import new annotations

### ISSUE THREAD

**Issue by EtienneDavid** [jsbroks/coco-annotator#261]
Hello,

First, thank you very much for this great job !

1- I struggling to understand how to import new annotations on a dataset.

I'm currently running my own instance with docker-compose on a dedicated server.

When using the import button, the task seems to not start.
When i want to add an annotation with the API, i'm struggling to authenticate. When I try from the swagger API tester, it seems the endpoint doesn't work.

2- I'm also strugging to export the annotation with  the API from the python requests package. All authentification methods i've found on internet fail

I feel i'm doing something wrong here but more documentation on importing and exporting annotations are most welcomed. I'm willing to help to documentate this part but I need some clue first :)

**Comment by EtienneDavid** [comment]
Or maybe it's not designed to receive external API call ? All my trials to get an authentication have failed ... Any clue is really welcomed !

**Comment by kevdagoat** [comment]
I am currently having the same problem with authentication

**Comment by jsbroks** [comment]
You should be able do login by a post request to call `/api/user/login` with `username` and `password` in the body

**Comment by jsbroks** [comment]
Could you share more information about the taak not starting? Any output in terminal?

**Comment by EtienneDavid** [comment]
Hello,

1- Thank for your advise. I finally understood how the authentification process works ! I was also missing the json parameter from requests. Here is a minimal example for others, i will propose a more documented section on the wiki.

`import requests
login_request = requests.post('http://yoururl:5000/api/user/login', json={ 'username':'mynameisgroot','password':'mypasswordisgroot'} )

print(login_request.status_code, 200)
print(login_request.cookies)

url = 'http://yoururl:5000/api/dataset/4/coco'
thing_request = requests.get(url, cookies=login_request.cookies)
print(thing_request.text)
`

2 - I think it was linked to #216 . My guess is that tasks stop working when no space is left on the server and / or CPU power. After rebooting on a more powerful server it seems to work perfectly !

Again, beautiiful work on the tool !

**Comment by trs96** [comment]
@EtienneDavid could you please tell me, how you imported new annotions through your code?
I'm struggling to find the correct import-process for importing..
