### ISSUE TITLE
Upload annotations with isbbox=True not working

### ISSUE THREAD

**Issue by EtienneDavid** [jsbroks/coco-annotator#265]
Hello,

I'm struggling with the upload of former bbox on the platform. 
Everything iis going well, but the property "isbbox"is not loaded. In data.py I add a line to get the property and export it to the database, but when it's on the mongodb, it has lost the property and it's a polygon without isbbox. 

The consequence is that I can not move the bbox as a bbox created with the tool, which is problematic for pre-annotation purposes. 

I tested it on the stable and latest build.

Do you have any clue on iit ?

Best, 

Etienne David

**Comment by jsbroks** [comment]
@mubashirhanif any idea?

**Comment by mubashirhanif** [comment]
@EtienneDavid I don't understand the problem exactly, may be if you could elaborate a step by step process to reproduce the issue, that might help me pin down the problem.
I tried the current build and it was working as expected.

**Comment by EtienneDavid** [comment]
Thank for working on the problem.

The minimal example:
Step 1
- I initiate a new VPS with Ubuntu 18.04
- clean install of docker with snap + git clone of coco-annotator
-  I launch docker-compose up
- I create a dataset and annotations
- Export COCO json

Step 1
- I initiate a new VPS with Ubuntu 18.04
- clean install of docker with snap + git clone of coco-annotator
-  I launch docker-compose up
- I create the same datasrt
- Import COCO json

The imported annotations are not considered as bbox.

How is exported the bbox ? Does it use imantics ? From what i've seen imantics doesn't import isbbox property either @jsbroks . I could add this part to insure compatibility between imantics and coco-annotator.

**Comment by jsbroks** [comment]
imantics is not used in any of the import or export processes.

The pr should fix the issue.

If you want to add the functionality to imantics it would be to simply check if the coco format has that flag a creating a BBox object inside of a Segmentation

**Comment by EtienneDavid** [comment]
Ok perfect, I've seen the PR, I think I understand better the process. Thank you very much @mubashirhanif  !
