### ISSUE TITLE
v0.10.6 - esc key no longer cancels a current polygon

### ISSUE THREAD

**Issue by EMCP** [jsbroks/coco-annotator#271]
I have gotten used to ESC canceling a polygon that is currently being drawn that I want to cancel.

It now no longer seems to work, and I do not see a button to cancel it in the settings page.

**Comment by schwabse** [comment]
Same issue here.

**Comment by kevdagoat** [comment]
I am also experiencing the same problem. I have replicated the issue on both Firefox and chrome

**Comment by matt-deboer** [comment]
@EMCP @schwabse @kevdagoat Are you all still seeing the same issue? 

This _should_ be fixed after the recent keypoints update...
