### ISSUE TITLE
Import COCO annotations

### ISSUE THREAD

**Issue by skywalkerisnull** [jsbroks/coco-annotator#280]
Hello,

I am in the process of writing a script up to convert a huge existing tags/assets from one format into COCO. I am wanting to import these into coco-annotator for validation, to build upon etc. and have a few questions around the behavior of the import of a COCO annotation file:

1. In the coco file under categories, do the category ID's need to match to any existing categories? If not, will it try and match based on name, and if it can't find it, will it automatically create a new one? (same goes for image_ids and annotation_ids), and what happens if the ID's clash, but the names are different?

2. Do we need to have the images already loaded into the datasets?

3. If the whole image has been given a "label" and we want to make use of the coco-annotator image label, how would we structure the coco json file? Looking at a test export, it seems to be missing the annotations with the corresponding category and image(s).

After I have finished up making it all work, I intend on writing out some of documentation in the wiki to help others in the same/similar position.

**Comment by jsbroks** [comment]
1. Categories to do not need to match. Categories are [matched based on names](https://github.com/jsbroks/coco-annotator/blob/8f809579465d3d83ef9aef70712355b0aafafd61/backend/workers/tasks/data.py#L160). Any categories that are not found (based on names) will be created. IDs in the coco are ignored in favor of the ones in the database. This is to stop collisions.
2. Yes
3. The import tool does not handle labels. Using the label tool adds a custom field onto the image, with the label ids (this is a custom format)

**Comment by skywalkerisnull** [comment]
Thank you @jsbroks, looks like I can't edit the wiki to add in this info and a bit of a process to make it easier for other people :(

**Comment by jsbroks** [comment]
You should be able to now. Thanks for letting me know.

Also [imantics](/jsbroks/imantics) may be useful.

**Comment by EtienneDavid** [comment]
Also maybe #261 can help you

**Comment by Angel-Ceballos** [comment]
Hi is there a test script that shows how to transform a mask (multi-class or binary) to coco annotator format? I am working on semantic segmentation and wanted to correct the outputs of my Unet with the annotator tool. Thanks!

**Comment by uwer** [comment]
@skywalkerisnull - did you ever get to update the (any) wiki to document the structure of the coco annotations to make the import work ? I am struggling to get the images found run in docker (and the path is correct within the container path).

**Comment by guilhermecorreagv** [comment]
I have tried many tools to convert from a YOLO dataset to the COCO json, but still no success in importing it. Did anyone manage to find a clean solution?
