### ISSUE TITLE
Don't publish a webui when it's not ready for production

### ISSUE THREAD

**Issue by YacobBY** [jsbroks/coco-annotator#281]
Can't even import my own image what's the point of this? To show that you have a database?

**Comment by kevdagoat** [comment]
???

Image upload from GUI is not supported

**Comment by YacobBY** [comment]
"Check out the demo of our car, only the wheels are missing".

**Comment by kevdagoat** [comment]
The demo is not for you to annotate your images, it is “for you to check out the cars internal and external features”

If you really want a good demo, just install it yourself!!
