### ISSUE TITLE
I cant import any images

### ISSUE THREAD

**Issue by zhengrenjiechn** [jsbroks/coco-annotator#286]
hello, i'm learning to use the coco annotation . Successfully install docker and arrive at the interface ,i can create a new datasets but the 'import' button has no response .Im appreciated if anyone give some suggestions for this issue.
my env :
ubantu16.04
docker 19.03.4,build 9013bf583a
docker-compose 1.24.1,bulid 4667896b
![image](https://user-images.githubusercontent.com/57652608/68643145-60075200-054b-11ea-98fd-94176ade0965.png)

**Comment by jsbroks** [comment]
You need to place the images in the datasets folder. The import button scans the directory and imports any times

**Comment by aowais2** [comment]
I am faced with the same problem. I went down the issues list, and found that some others previously couldn't access the directory in datasets because permission is denied.
There was talk about how to SFTP into it, or use chmod or something to get access to the folder, but it went over my head. Is adding images something of a paid feature by any chance?

**Comment by jsbroks** [comment]
@aowais2 there are no paid for features.

What operating system are you using?

**Comment by aowais2** [comment]
I'm using Ubuntu 18.04 with Docker Compose 1.24.1 and the latest Docker

**Comment by aowais2** [comment]
In more detail, here's the error I received.
Error opening file “/path/to/coco-annotator/datasets/humanoid/nao.png”: Permission denied
I tried using "sudo chmod +x <filename>" to change user permission

**Comment by kevdagoat** [comment]
Have you even properly configured the mount point for the images?

Have a look in docker-compose.yaml

**Comment by aowais2** [comment]
@kevdagoat I probably haven't. Is there a resource where I can learn how to configure the mount point? So far, I have installed Docker and Docker Build, and used "sudo dockerd" to start the docker up, and then used the Chrome browser to go to the localhost URL

**Comment by kevdagoat** [comment]
Ok it is a permissions problem.

cd to where your container files are and run:

sudo chmod -R 777 ./datasets
sudo chmod-R 777 ./models

**Comment by aowais2** [comment]
@kevdagoat Thanks, it actually works. Appreciate your help. I think I'll add these details in the wiki if I can

**Comment by kevdagoat** [comment]
Ok, your very welcome :)
