### ISSUE TITLE
I can't use any tools.

### ISSUE THREAD

**Issue by Michael-J98** [jsbroks/coco-annotator#288]
![image](https://user-images.githubusercontent.com/57127813/68675959-f3647580-0593-11ea-9b3a-c75cc4f52f43.png)

As you can see, why the tool icons on the left bar are invalid. I can't activate them by either clicking or keyboard shotcuts.

**Comment by jsbroks** [comment]
You have no categories selected. You need to create categories before you can annotate

**Comment by Michael-J98** [comment]
> You have no categories selected. You need to create categories before you can annotate

Oh, my bad. It works. Thank you!!!
