### ISSUE TITLE
can not export 

### ISSUE THREAD

**Issue by satchelwu** [jsbroks/coco-annotator#291]
i tried the dataset dropdown menu to select "Download COCO" 
multiple task running...

the task could not  be canceled ,  in the datasets folder ,there was no *.json saved . I also used command "chmod 777 ./datasets/mydataset", still nothing worked,

**Comment by jsbroks** [comment]
Have you used the method mentioned in #237

**Comment by kevdagoat** [comment]
I have this problem if annotator-workers is not running

**Comment by satchelwu** [comment]
@kevdagoat I opened the Kitematic  and found that the annotator-workers was indeed not running.  Thanks very much, @kevdagoat, @jsbroks
