### ISSUE TITLE
remote annotation worker

### ISSUE THREAD

**Issue by wmpauli** [jsbroks/coco-annotator#298]
I'm trying to use a maskrcnn model that I have deployed as a webservice for semi-automated annotation. I appear to be unable to figure out how to specify the api url correctly. I keep on getting this error: "Could not read data from URL".

Note, I have been able to use the built-in maskrcnn model by specifying the API url as described in Issue [176](https://github.com/jsbroks/coco-annotator/issues/176#issue-428339049).

For debugging purposes, I tried to use the built in model, but specifying the URL as a http address, i.e. http://localhost:5000/api/model/maskrcnn. I do get the same error if I do that.

**Comment by wmpauli** [comment]
I'm generally (also) curious how I could avoid the "Authorization required" error when calling the API directly with curl. I get it even if I include username and password in the header (-H) or directly via curl (--user/-u). The only curl command that works seems to be user login, but then I still get this error afterwards.

**Comment by kevdagoat** [comment]
﻿Authorisation is done through a specific API path, not just through any path.
