### ISSUE TITLE
semi-automated annotation with bounding boxes or keypoints

### ISSUE THREAD

**Issue by wmpauli** [jsbroks/coco-annotator#299]
Is it possible to use the model-based annotation feature for semi-automated labeling with keypoints and/or bounding boxes?

I noticed that the call to the built-in maskrcnn returns bounding box coordinates, but they don't seem to be used. I have a model that would also return keypoints, but before I try to figure out how to make it work, I'd rather first know whether the keypoints would be used.

If this is not supported I would be happy to contribute to enable keypoints. In that case I would be grateful for any pointers towards the relevant parts of the repo.

**Comment by jsbroks** [comment]
The values returned from the model are processed in the [AnnotateButton file](https://github.com/jsbroks/coco-annotator/blob/fc5ab4c0ed2fc4578f4114d5f035d2b925f0c7b3/client/src/components/annotator/tools/AnnotateButton.vue#L41). It has not been tested if the maskrcnn returns key points will be process properly. However, the logic to do so is there.

When clicking the annotating process, an POST API request is created which sends the current image to the URL you set in the settings. The response is assumed to return coco format which is processed and inserted into the annotator.

- Sending API request (done in [AnnotateButton.vue](https://github.com/jsbroks/coco-annotator/blob/fc5ab4c0ed2fc4578f4114d5f035d2b925f0c7b3/client/src/components/annotator/tools/AnnotateButton.vue#L35)) 
- Adding annotations to Annotator View ([AnnoteButton.vue](https://github.com/jsbroks/coco-annotator/blob/fc5ab4c0ed2fc4578f4114d5f035d2b925f0c7b3/client/src/components/annotator/tools/AnnotateButton.vue#L67) calls addAnnotation located in the [Annotator.vue](https://github.com/jsbroks/coco-annotator/blob/fc5ab4c0ed2fc4578f4114d5f035d2b925f0c7b3/client/src/views/Annotator.vue#L789) file

This information should help you get started with the codebase

**Comment by wmpauli** [comment]
@jsbroks , thank you for your response. It is indeed possible to get keypoints from a remote worker with the AnnotateButton. The points are stored and exported correctly. The skeleton is also drawn according to my coco dataset definition. The one thing that is not happening is setting keypoint_labels. This doesn't affect the json export of the dataset, so I think it is not a blocker. From what I can tell, the reason that keypoint_labels are not considered is that the api/annotation doesn't support keypoint_labels, and further downstream the database.AnnotationModel also does not use keypoint_labels. Great tool! Now I can use my own custom model for semi-automated annotation.

**Comment by sebo313** [comment]
Hi @wmpauli sounds great! Could you share your work regarding keypoint annotation api? I am currently trying to implement the same and cant get it running :/

**Comment by Tjay456** [comment]
@sebo361 have you get it working with the URL API ?
I have seen you have written another Issue where you have implemented the Pose Estimation into the Repo.
I have a very similar use case. Is it not possible to use the Endpoint function for adding Keypoints?

I have tried it, it does not return an error, but just nothing happens when my Endpoint returns the results in COCO json format.
