### ISSUE TITLE
Windows docker-compose gets unexpected mongo exit code 14

### ISSUE THREAD

**Issue by jsbroks** [jsbroks/coco-annotator#30]
When running docker-compose on windows mongo fails:

`annotator_mongodb exited with code 14`

**Comment by jsbroks** [comment]
Cannot use a volume shared to the Windows host. Current work around is to remove

```YAML
        volumes:
            - './data/db:/data/db'
```

from the `docker-compose.yml`.

> WARNING (Windows & OS X): The default Docker setup on Windows and OS X uses a VirtualBox VM to host the Docker daemon. Unfortunately, the mechanism VirtualBox uses to share folders between the host system and the Docker container is not compatible with the memory mapped files used by MongoDB (see vbox bug, docs.mongodb.org and related jira.mongodb.org bug). This means that it is not possible to run a MongoDB container with the data directory mapped to the host.
> - Docker Hub ([source](https://github.com/docker-library/docs/blob/b78d49c9dffe5dd8b3ffd1db338c62b9e1fc3db8/mongo/content.md#where-to-store-data))

**Comment by EduardoDornel** [comment]
This was fixed with Virtual Box 6.0.6
https://www.virtualbox.org/wiki/Downloads
