### ISSUE TITLE
Issue with exported COCO annotations

### ISSUE THREAD

**Issue by mgarbade** [jsbroks/coco-annotator#304]
The exported data seems not to be usable by the COCO-API from scratch, because the "skeleton" definition in the exported json file seems to be wrong:

`"skeleton": [[4, 3], [9, 15], [7, 13], [14, 9], [15, 13], [32, 33], [21, 20], [18, 19], [12, 13], [9, 7], [14, 15], [17, 5], [5, 3], [14, 16], [8, 4], [8, 12], [14, 13]]`
vs
`"skeleton": [[16,14],[14,12],[17,15],[15,13],[12,13],[6,12],[7,13],[6,7],[6,8],[7,9],[8,10],[9,11],[2,3],[1,2],[1,3],[2,4],[3,5],[4,6],[5,7]]`

In the original `person_keypoints_val2017.json`. By changing the entries manually in the json file I could finally use `cocoGt.showAnns(anns)` from the coco-api to plot the data.

Not sure were the skeleton was defined earlier... I'll keep on digging

**Comment by matt-deboer** [comment]
@mgarbade still a problem with the keypoints update?

**Comment by mgarbade** [comment]
Yes this fixed it, thank you
