### ISSUE TITLE
Tasks are running indefinitely and cannot be stopped

### ISSUE THREAD

**Issue by KNaudin** [jsbroks/coco-annotator#307]
Hello. I have found no help on the wiki concerning this issue. I have multiple tasks running that cannot be stopped. I tried deleting them via the API but I'm getting a bad request error (400)
```
{
  "message": "Task is not completed"
}
```
Is there a way to stop a non-completed task ?

**Comment by jsbroks** [comment]
No... you could modify the database directly to stop them

**Comment by KNaudin** [comment]
I put them all to failed and completed manually, then was able to delete the tasks.

It is weird that the tasks do not consider themselves failed when they can't reach a directory that does not exist anymore, or don't time out after trying to import a JSON file for over a month.

**Comment by MPrince-Horo** [comment]
@KNaudin @jsbroks Hi, can you please tell me where and how to put them to failed, because they are starting to stack up and it is becoming an inconvenient?

**Comment by 1994sugar** [comment]
Hi, Did you solve this problem？？

**Comment by 1994sugar** [comment]
> No... you could modify the database directly to stop them
Hi, could you tell me how to solve this problem? I meet the same problem that "Task is not complete"
