### ISSUE TITLE
How to import image to a newly created dataset?

### ISSUE THREAD

**Issue by HaKLMTT** [jsbroks/coco-annotator#31]
Thanks for your open project coco-annotator in github.

I have one question here. 
(OS: Linux version 4.15.0-29-generic (buildd@lgw01-amd64-057) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 )

How to import image to a newly created dataset?

What I did is followed:
1.put several images under directory "./data/datasets/test"  
2.create one dataset named "test"
But it seems not working. Always showing "No images in dataset". 

Need your help here.

**Comment by jsbroks** [comment]
Try the following:

1. Start the application `docker-compose up` (the application must be running in order for it to notice changes in the directory)
2. Create a dataset object
3. Place the images in the newly created directory location at `/data/datasets/<dataset_name>`

**Comment by HaKLMTT** [comment]
It works. The point is Create a new dataset firstly, then put images under the corresponding directory. As you said, only by this way, the process can notice the change under the directory.

**Comment by NicksonYap** [comment]
It took me a long time to figure out how to import images.

Turns out u copy images into a folder locally

Can't there be an upload button, or at least a notice in the UI to explain?

**Comment by jsbroks** [comment]
Its explained in the [wiki](https://github.com/jsbroks/coco-annotator/wiki/Usage#Importing-Images), also issue #29  is intended to fix this issue.

**Comment by NicksonYap** [comment]
@jsbroks

I skimmed through it mulitple times before finding this issue

Turns out you did mention:

Navigate to the datasets directory located at the root of this project.

Perhaps we'll make it: (and place in the beginning)

To Import Images - Navigate to the `datasets` directory located in the **root** of this project.

(And maybe place it before the pros and cons text)
