### ISSUE TITLE
Tasks are running?

### ISSUE THREAD

**Issue by Michael-J98** [jsbroks/coco-annotator#313]
Is that normal? Are there indeed any tasks running now?
![tasks](https://user-images.githubusercontent.com/57127813/72237739-81052580-3616-11ea-8f71-807ced2f5427.png)
Besides, is this tab where I download the .json file after the export tasks are finished?
![export](https://user-images.githubusercontent.com/57127813/72238022-7eef9680-3617-11ea-9db9-e10b62af23a1.png)

**Comment by Michael-J98** [comment]
well, now I can download the json file after reinstalled  it, but the number of running tasks is still confusing to me now.

**Comment by KNaudin** [comment]
No they are not. I had the same issue, check issue #307 
I used a mongoDB interface to remove these manually.

**Comment by jsbroks** [comment]
Yes that is the tab to download exports.

You can click on the task to view more information.

**Comment by Michael-J98** [comment]
> No they are not. I had the same issue, check issue #307
> I used a mongoDB interface to remove these manually.

Thanks a lot.

**Comment by Michael-J98** [comment]
> Yes that is the tab to download exports.
> 
> You can click on the task to view more information.

Thank you. I checked out the json file and noticed that there is a “iscrowd” key whose default value is False. How can I turn it to True?

**Comment by jsbroks** [comment]
You'll have to write a mongodb query to change

**Comment by Michael-J98** [comment]
> You'll have to write a mongodb query to change them

which means only polygon annotation is supported while RLE is not?

**Comment by Michael-J98** [comment]
Thank you for your effort.

**Comment by bpmsilva** [comment]
> No they are not. I had the same issue, check issue #307
> I used a mongoDB interface to remove these manually.

@KNaudin, could you detail more how did you do that? Thanks in advance
