### ISSUE TITLE
extra keypoint inserted

### ISSUE THREAD

**Issue by songkevinc** [jsbroks/coco-annotator#315]
Hello,

Thanks a bunch for making this tool. It's amazing!

I'm using the development build currently. I was doing some keypoint and segmentation annotations and I realized that when I use shortcuts (arrowup and then K) to use keypoint annotator, the annotator requires me to click an extra point before it starts to go through the labels that I created for keypoints.

It doesn't seem to be a problem if I click the instance I created and click on the top label (in my case, nose) and then start annotating. Thought I should share, and hope you guys could help me figure out how to fix this. 

Thanks.

**Comment by matt-deboer** [comment]
@jsbroks feel free to assign me
