### ISSUE TITLE
DEXTER tool not working

### ISSUE THREAD

**Issue by ron-weiner** [jsbroks/coco-annotator#318]
Hey
I am trying to use the DEXTER tool but it throws me an error.
The interface let me mark the dots and then it just erase them.
(I am using a gpu server)

Here is the error:
Traceback (most recent call last):
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
annotator_webclient |     rv = self.dispatch_request()
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
annotator_webclient |     return self.view_functions[rule.endpoint](**req.view_args)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
annotator_webclient |     resp = resource(*args, **kwargs)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
annotator_webclient |     return self.dispatch_request(*args, **kwargs)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
annotator_webclient |     resp = meth(*args, **kwargs)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
annotator_webclient |     return func(*args, **kwargs)
annotator_webclient |   File "/workspace/webserver/api/models.py", line 63, in post
annotator_webclient |     result = dextr.predict_mask(image, points)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/dextr-0.0.1-py3.6.egg/dextr/model.py", line 46, in predict_mask
annotator_webclient |     input_dextr = np.concatenate((resize_image, extreme_heatmap[:, :, np.newaxis]), axis=2)
annotator_webclient | numpy.AxisError: axis 2 is out of bounds for array of dimension 2

**Comment by EtienneDavid** [comment]
Did you download the model with the .sh ?
