### ISSUE TITLE
Can't copy keypoints

### ISSUE THREAD

**Issue by latkins** [jsbroks/coco-annotator#319]
I've been using the development build, and experimenting with keypoint annotation. On fresh build, I can't copy keypoint annotations between images. I can copy e.g. bounding boxes.

**Comment by matt-deboer** [comment]
@jsbroks I can take this...

**Comment by latkins** [comment]
I'm keen to help with this -- not really sure where to start, however. Can you point me towards the relevant part of the codebase?

**Comment by matt-deboer** [comment]
Sorry for delay on this; just haven't had the spare time. It was actually a pretty quick fix.

It looks like they _were_ copying, but only if there was an annotation or bbox present on the annotation.
The fix should be in shortly... ( #333 )
