### ISSUE TITLE
labeling mode question

### ISSUE THREAD

**Issue by JeongChanwoo** [jsbroks/coco-annotator#322]
I tried to label via labeling mode and export, but the result is not registered in json.
Is it necessary to do segmentation annotation to register in json file?

**Comment by EtienneDavid** [comment]
Can you described what are your outputs ?

**Comment by JeongChanwoo** [comment]
Data that is only labeled without annoation cannot be found in the export json.
![image](https://user-images.githubusercontent.com/30068081/73505731-ab2c5500-4416-11ea-993c-46226614b5fe.png)

**Comment by jsbroks** [comment]
It shouldnt be, but to register as coco format yes, segmentation is required.

**Comment by JeongChanwoo** [comment]
If so, It's not enough to generate and classify data using only the labeler module.

**Comment by jsbroks** [comment]
Closing for now. please check latest to see if issue is fixed.

**Comment by Apollo-XI** [comment]
@jsbroks I have the same issue. Labels aren't exported. I tried:
- 1 label -> image path doesn't appear in the json neither the label. Moreover, Dataset UI doesn't detect that the image is annotated. 
- 1 label + 1 bbox -> image path + bbox are in the json but not image label.

For me, labeling images is useful to train an image classifier that runs before the object detection model. So,  having all annotations in one place would be beneficial. Currently, I using LabelMe for image labels and Coco Annotator for object detection labels.
