### ISSUE TITLE
Page crash in segmentation

### ISSUE THREAD

**Issue by Daubige** [jsbroks/coco-annotator#324]
Hello,

I use the Coco Annotator tool to train a segmentation model.
I label 1024*1024 .JPG images with the brush tool.
Then encounter big bugs. During the first minute everything goes well. Then the tool becomes slower and slower (unusable) and the page crashes.
During the bug phase, each click makes the processor use increases.  
I didn't find any link related to the use (number of polygons displayed, labeling speed, zoom...).
Refreshing the page doesn't make things better. But when the page crashes and relaunches everything goes smoothly during 1min.

Have you ever encountered this problem? Do you have any ideas? It could be  the 'cache' memory

Here is the link of the video illustrating my comments : https://youtu.be/MA3uOXsmqL4

**Comment by jsbroks** [comment]
Please see #210 and #150

**Comment by EtienneDavid** [comment]
From what i understand, the problem is linked to paper.js and beyond the scope of this project ?
