### ISSUE TITLE
Image size limit

### ISSUE THREAD

**Issue by pedromonteiro18** [jsbroks/coco-annotator#328]
Hello, I am trying to upload an image 181.2MB in size as there is apparently to size limit, however it does not seem to upload. When it trying to add the file this happens:

[error] <0.911.0> closing AMQP connection <0.911.0>
annotator_message_q | missed heartbeats from client, timeout: 60s

The issue may be due to do with:

PIL.Image.DecompressionBombError: Image size (544997376 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.

as this is the only warning I receive. 

Is there a way to fix this so that images of any size can be uploaded?

**Comment by jsbroks** [comment]
This is a limitation of PIL 
https://stackoverflow.com/questions/51152059/pillow-in-python-wont-let-me-open-image-exceeds-limit

You could run a dev build and do as suggested from stackover flow. But I would recommend split the image up into sub images or downsize the image and scalling the annotations afterwards.
