### ISSUE TITLE
Where are the saved annotation?

### ISSUE THREAD

**Issue by JeanHoroma** [jsbroks/coco-annotator#329]
I have a problem with my Docker and I can't log anymore on coco-annotator. I want to reinstall everything (docker, and coco), but I don't to loose my annotation that I didn't export. If it's possible, where are the annotation saved so I can backup them?

Thank you.

**Comment by jsbroks** [comment]
Annotations are stored in a docker volume. Look at the docker-compose.yml for more information

**Comment by JeanHoroma** [comment]
Thank you for your answer, but I'm sorry, I really don't understand how to work with docker. 
There is many volume in the docker-compose.yml, so which one is it? And what should I do once I find the right path.

**Comment by JeanHoroma** [comment]
In fact, one of my problem is this error message when I do docker-compose up:

annotator_webclient | [2020-01-17 22:10:36 +0000] [25038] [INFO] Booting worker with pid: 25038
annotator_webclient | [2020-01-17 22:10:36 +0000] [25038] [WARNING] MaskRCNN model is disabled.
annotator_webclient | 2020-01-17 22:10:37.023527: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.

It does that in a never ending loop, and I can't start coco-annotator in my browser.

My second problem is I got a high cpu usage even when I do nothing with my computer (whenn it just got booted) and my htop detect this command take the cpu:

/usr/local/bin/python /usr/local/bin/gunicorn -c webserver/gunicorn_config.py webserver:app --no-sendfile --timeout 180

I think it's link one of coco dockerfile.

Thanks

**Comment by piebro** [comment]
To get the path of the docker volume you can use
```bash
sudo docker volume ls
``` 
to list all docker volumes. There you will find a volume name similar to ```coco-annotator_mongodb_data``` with the name you can get the path with
```bash
docker volume inspect coco-annotator_mongodb_data
```

**Comment by JeanHoroma** [comment]
Ty for your answers, everything works perfectly now.
