### ISSUE TITLE
Keypoint Annotations Not Saving

### ISSUE THREAD

**Issue by WillJStone** [jsbroks/coco-annotator#332]
I have created a custom category and given it several keypoint labels. I select my dataset, select an image, and label it successfully. When I navigate to another image with the left/right arrow in the right side toolbar and then come back, my annotation is gone. If I press the 'save' button, my annotation immediately disappears.

Any suggestions? Aside from this issue, this is a really great tool.

Edit: To clarify, other annotations such as bounding boxes save just fine.

**Comment by geoffreysteven** [comment]
I have the same problem, not sure the cause.

**Comment by jsbroks** [comment]
What verions are you using?

**Comment by WillJStone** [comment]
As far as I know I am using the latest version. I followed the installation instructions exactly.

**Comment by jsbroks** [comment]
Could you share your docker-compose.yml file (just so I can confirm)? If you followed the wiki instructions that will be the stable build.

**Comment by geoffreysteven** [comment]
version: "3"
volumes:
  mongodb_data:
    external: false

networks:
  cocoannotator:
    external: false

services:
  webserver:
    image: jsbroks/coco-annotator:webserver-stable
    container_name: annotator_webclient
    restart: always
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=RandomSecretKeyHere
      - FILE_WATCHER=true
    volumes:
      - "./datasets:/datasets"
      - "./models:/models"
    depends_on:
      - database
      - workers
    networks:
      - cocoannotator
  workers:
    container_name: annotator_workers
    image: jsbroks/coco-annotator:workers-stable
    volumes:
      - "./datasets:/datasets"
    depends_on:
      - messageq
      - database
    networks:
      - cocoannotator
  messageq:
    image: rabbitmq:3
    container_name: annotator_message_q
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - cocoannotator
  database:
    image: mongo:4.0
    container_name: annotator_mongodb
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "mongodb_data:/data/db"
    command: "mongod --smallfiles --logpath=/dev/null"
    networks:
      - cocoannotator

**Comment by WillJStone** [comment]
That .yml file is the same as mine.

**Comment by jsbroks** [comment]
Try changing all images names to `*-latest` (instead of currently `*-stable`)

Make sure to back up your data, just incase you need to revert.

**Comment by WillJStone** [comment]
This seems to work. Thanks very much for the quick response!
