### ISSUE TITLE
Import annotations works only with smaller batches of images

### ISSUE THREAD

**Issue by JeanHoroma** [jsbroks/coco-annotator#337]
Hi, 

We have many datasets with different number of images in them. The annotation were created in a first computer, then we transferred the datasets in a second computer with the .json files. 

Our problem is when we try to import the annotations link to a dataset, it only work with the smallest datasets (fewer than 400 images) and smallest .json files (lower than 100 MB). Those import jobs took less than 5 minutes to be done. When we try to import annotations of datasets with 675 images and more (it can goes to 4000 images) with .json between 140 MB to 1GB, the import task just never goes on, even after an hour of waiting. 

In the task menu (see below), when we click on the individual task, nothing appears, and we are not able to delete them.  

![image](https://user-images.githubusercontent.com/47372176/75004580-a23d0b00-5439-11ea-8c92-5fb40fe31782.png)

The question is: is there a limit of images we should put in a dataset with a limit of size to a .json file to make it work, or the problem comes from something else?

Btw, thank you very much for your help and your great software.

**Comment by dreaquil** [comment]
Hi @JeanHoroma ,

I'm having other issues with the importer as detailed in #335 . Do you see the annotations immediately appear in your dataset view when you import or do you need to manually cycle through them for them to load?

**Comment by JeanHoroma** [comment]
@dreaquil  
Sorry for the delay, I didn't got time to work on this project lately. To answer your question, I don't have to manually cycle every images to see the annotations.

@jsbroks 
I saw an error message in the terminal with the docker, saying that there is maximum configured of 128 MB for a message (probably meaning the JSON with the annotation). Is there a way to augment that maximum, and if so, how do I do it?
Thank you very much!

**Comment by JeanHoroma** [comment]
We found a way to reduce our JSON. In fact, they were too big because they were produced by a RCNN that putted a point to every neighbored pixels to create the polygon. By reducing the number of point to create the polygon, we obtain almost the same polygon shape with a JSON 50 times smaller.

Now, our JSON files are all under 128MB.

**Comment by Alloooshe** [comment]
I still got a size related error when uploading a 6MB json file to  the docker, I am not sure how could you get 128MB, did you run it locally or in a server ?
