### ISSUE TITLE
keypoint output is empty

### ISSUE THREAD

**Issue by songkevinc** [jsbroks/coco-annotator#338]
Hello,

I haven't had this issue before, but for some reason now, when I export COCO and look at the JSON file, it's empty as shown below:

![image](https://user-images.githubusercontent.com/24256356/75386783-4991c600-58b0-11ea-9216-f38df1a78858.png)

I think I just recently ran docker-compose pull and git pull, but not sure why my data is not saving.

**Comment by jsbroks** [comment]
If you revert you docker container does it work again?

**Comment by songkevinc** [comment]
Sorry, how do I go about doing that?

Also, I changed the permission on all the files in coco-annotator directory, and now I can't log in... Any suggestions on how I can fix that?

**Comment by songkevinc** [comment]
I might just try to re-download coco-annotator repo and re-install. Is there a good way to save the dataset + annotation without exporting to coco and transfer to the new git repo?

**Comment by jsbroks** [comment]
You can do that, but I think the problem is in the latest build I pushed... might not be as stable as I though...
in the docker-compose file replace `-stable` with `-0.10` to change back to v0.10
You will have to google around for how to backup docker volumes

no idea about the permissions

**Comment by songkevinc** [comment]
reverting back to 0.10 worked. Thanks!

**Comment by mgarbade** [comment]
reverting go 0.10 didn't work for me. Still export wasn't working. Instead I could shut down the annotator and instead launch the development build, where export was working. So thankfully my data could be saved.

**Comment by mgarbade** [comment]
In 0.10 exporting works but a new serious bug appeared: Annotations are getting eating when going to the next image (shortcut "n") and then returning to previous (shortcut "p") ... which is a serious issue

**Comment by jsbroks** [comment]
Check latest commit and lmk if the issue is fixed.

**Comment by mgarbade** [comment]
Thanks a lot for the fix!
- Exports are working in `docker-compose.dev.yml` version

FYI (not urgent):
- Exports issue persists in production version
