### ISSUE TITLE
Not all images are exported

### ISSUE THREAD

**Issue by Renart-fox** [jsbroks/coco-annotator#342]
Hello.
I've annotated quite a number of images, 252 to be exact. Each one of them has 1 of 4 category annotated.
When I try exporting the resulting COCO file, only 192 of them are exported. Each image does not contain the same category, so I don't think it's related to the category.

I have no idea what's happening and I need to export that data ASAP.

**Comment by jsbroks** [comment]
Please take a look at the other issues #338 #340

**Comment by jsbroks** [comment]
Consider reverting to 0.10

**Comment by KNaudin** [comment]
Nevermind it actually is related to a category.

I have a category that exists in 2 different datasets, and only this category is not exported.
This bug seems different from the other issues.

**Comment by jsbroks** [comment]
Okay, could you provide more detail

**Comment by KNaudin** [comment]
Sure thing !

I can't show you the images but:
- The thumbnail show the object with a purple mask. Below the image's title is written "No annotation."
- As you can see here, the annotation has an ID and is not marked as "(Empty)
![Screenshot_20200305_164532](https://user-images.githubusercontent.com/17451603/75998193-bc2e2180-5f00-11ea-866e-dffa4b452ab0.png)

Now if I download the annotation file, we can see that the annotation actually exists:
```
{"images":[{"id":238395,"dataset_id":33,"path":"imagename.png","width":1920,"height":1080,"file_name":"imagename.png"}],"categories":[{"id":42,"name":"pot","supercategory":"","color":"#531fed","metadata":{},"keypoint_colors":[]}],"annotations":[{"id":219695,"image_id":238395,"category_id":42,"segmentation":[[1007.4,756.7,1004.2,872.8,991.4,900,977.4,912.8,946.1,919.6,922.9,920.4,901.3,914.4,879.7,895.6,872.1,866.4,865.3,768.3,846.8,728.7,853.3,711,879.7,703.4,963.8,695.4,990.6,699,1010.2,714.7,1027,735.9,1021.8,746.7,1009,756.3]],"area":29896,"bbox":[847,695,180,225],"iscrowd":false,"isbbox":false,"color":"#eb4be1","keypoints":[],"metadata":{}}]}
```
Here is the dataset representation of the object:
![Screenshot_20200305_165121](https://user-images.githubusercontent.com/17451603/75998723-8c334e00-5f01-11ea-804a-7f83ce4ddab3.png)

**Comment by DerteTrdelnik** [comment]
as a temporary workaround try to go to Datasets and click on the three dots ... -> Download COCO
I have the same issue and this works for me (sorry did not look into what is happening under the hood or whether it is just luck based... maybe later or this can help someone debug the difference)

**Comment by KNaudin** [comment]
Thanks a lot @DerteTrdelnik , it does work! Still weird that this happens though.
