### ISSUE TITLE
Image are not detected as "annotated"

### ISSUE THREAD

**Issue by timofurrer** [jsbroks/coco-annotator#343]
I'm using the *local production docker-compose* setup (as described in the wiki) in version v0.11.0.

The problem is that the images I annotate are not detected as such.
The dataset has around 2k images each of them is about 200-500 KB in size.

The overview page shows:

![image](https://user-images.githubusercontent.com/1008252/76160504-00046f00-612b-11ea-8f36-9b5983091076.png)

And the "Statistics" page of that dataset shows "3" annotations (all in the same image), but no annotated image:

![image](https://user-images.githubusercontent.com/1008252/76160515-17435c80-612b-11ea-874f-84d159f6f6bd.png)

The image itself in the overview shows the annotations (in blue), but "no annotations" as a comment:

![image](https://user-images.githubusercontent.com/1008252/76160532-3e019300-612b-11ea-80bc-cd3ff84cc386.png)

Even though those are the ones reported in the statistics page. 
I've already tried this on several machines and installations, but it's the same issue everywhere.
Do I have to do anything else than "save" the image after annotating?

**Comment by timofurrer** [comment]
I've just noticed that this is the case only if I don't annotate all the category in an image. 

Isn't it possible to only annotate some categories in a single image?

**Comment by jsbroks** [comment]
This seems like a bug, shouldn't be happening

**Comment by timofurrer** [comment]
Is there a workaround for that? Can you point me towards where that bug might come from? Maybe I can implement a fix myself.

**Comment by waicool20** [comment]
I'm having the same issue here, also using docker compose setup.

**Comment by ettzzz** [comment]
Had the same problem annotating multiple categories. Any plan to fix it?

**Comment by yangkey87** [comment]
@jsbroks Sir, if you have time, please fix it, as we can relying on your tool to develop our model. Your effort is very appreciated!

**Comment by waicool20** [comment]
After pulling in the latest commits annotations on old images are still reporting as none and new images have wrong number of annotations reported

**Comment by tlalexander** [comment]
I am also affected by this bug. I just updated the docker containers last night and thats when the issue began. After discovering the issue today and then this thread, I've found that running the development build seems to solve the problem.

https://github.com/jsbroks/coco-annotator/wiki/Getting-Started#Development-Build

However there's a catch. My annotations made today on the buggy version still exist, but they do not show as being annotated in the tiled file view window nor register as annotated until I click on the image and view it in the editor. Once I load a previously buggy annotated image it registers as annotated. I have not found a mass way to fix my dataset as I've got some 20 randomly selected images with buggy annotations right now.

**Comment by tlalexander** [comment]
Hmm. I just realized my development build is ver 10.5, and the docker version earlier today was 11. So I think I misunderstood how the development builds work. I thought it would pull a bleeding edge docker version, but it must be just running from my git directory.

**Comment by waicool20** [comment]
The annotation stats seems to only be updated when the client saves. It's not calculated on the fly when doing a get request.
