### ISSUE TITLE
Performance issue with high number of annotations

### ISSUE THREAD

**Issue by EtienneDavid** [jsbroks/coco-annotator#344]
Dear Justin,

I've notice a serious performance drop when the number of images > 5000 and number of annotations > 600k.

The thumbnails process is too long and the thumbnails not that useful... Is it possible to drop completly this feature ? 
Is there anything that could cause such low performance ? 

My server has 8 RAM and 4 CPUs, I could have better but don't see why it's continuously freezing...

Best,

Etienne

**Comment by EtienneDavid** [comment]
I'm ready to propose a fork without thumbnail and see if it solve the performance problem... If you could indicate which part in the code to modify ?

**Comment by jsbroks** [comment]
https://github.com/jsbroks/coco-annotator/blob/0ab2c848e12c1ec4fe0cb013705795f6e14df966/backend/webserver/api/images.py#L135

```
        pil_image = image.thumbnail() if thumbnail else Image.open(image.path)
        image.flag_thumbnail(flag=False)
        
        pil_image.thumbnail((width, height), Image.ANTIALIAS)
        image_io = io.BytesIO()
```

To probably something like:
```
        pil_image = Image.open(image.path)
        
        pil_image.thumbnail((width, height), Image.ANTIALIAS)
        image_io = io.BytesIO()
```

**Comment by EtienneDavid** [comment]
Thank you very much :) I will take a look at it

**Comment by JeanHoroma** [comment]
@EtienneDavid

Hi, I'm having the same issue. Please, can you tell me if the solution work?

Thank you

**Comment by EtienneDavid** [comment]
@JeanHoroma sorry still didn't had the time to get a proper look at it ...

**Comment by DenysIsaiev** [comment]
I solve this problem by moving thumbs generation to celery task. Now it generates asynchronous without blocking user activities

**Comment by jsbroks** [comment]
Could you make a PR for this.
