### ISSUE TITLE
Performance with eraser tool

### ISSUE THREAD

**Issue by YumainOB** [jsbroks/coco-annotator#351]
I usually use the eraser to draw holes in masks or correct too broad annotations and I noticed. when the hole/correction is somehow large the GUI starts (quite quickly) to lag and can even bring the GUI to crash. For now to overcome this issue I have to save annotation really often and to use eraser in clic once-move-clic another time policy the brush policy being the better way to go to a crash.

Am I alone in this case or is there a way to correct this issue?

**Comment by jsbroks** [comment]
Same issue as #210
