### ISSUE TITLE
Use own pretrained model for semi-automated Annotations

### ISSUE THREAD

**Issue by sebo313** [jsbroks/coco-annotator#353]
Hi there and thanks for sharing the great work @jsbroks!

I would like to annotate my own images with a set skeleton keypoints. In order to annotate faster, I would like to use my own / a pretrained pose estimation model such as [github.com/ildoonet/tf-pose-estimation](https://github.com/ildoonet/tf-pose-estimation) for detecting keypoints which I will approve or adjust afterwards. Can somebody please explain me how to set this semi-automated annotation up? How do I include my own model or a standard pose estimation model?

**Comment by jsbroks** [comment]
Take a look at this [article](https://techcommunity.microsoft.com/t5/ai-customer-engineering-team/accelerate-your-end-to-end-ml-lifecycles-with-semi-automated/ba-p/1054432#.Xh_If2dSTFg.linkedin). You will need to create an api the returns coco json of the resulting keypoints

**Comment by sebo313** [comment]
Thanks @jsbroks for the article! I tried to integrate the [tf_openpose](https://github.com/ildoonet/tf-pose-estimation) model as a API in order to get the 18 COCO - Body keypoints. Please check my issue #358
