### ISSUE TITLE
add connected label not working

### ISSUE THREAD

**Issue by RePhil77** [jsbroks/coco-annotator#354]
First of all, thank you for the great work!

Adding connected labels to keypoints of my "person" category and clicking the "update" button does not seem work. The skeleton list in the exported json file remains empty and when editing said "person" category, the previous added connected labels do not appear.  

Any help would be appreciated :)

**Comment by danab** [comment]
If you are comfortable modifying the code I think the above PR will fix the issue.

**Comment by kinglintianxia** [comment]
@danab Thank you for the great work first!
After merge [#355](https://github.com/jsbroks/coco-annotator/pull/355) , clicking the "update" button   no errors ocurs , but the connections does not really update.
