### ISSUE TITLE
Add OpenPose API in Annotator for body keypoint detection

### ISSUE THREAD

**Issue by sebo313** [jsbroks/coco-annotator#358]
Hi @jsbroks , I tried to integrate the [tf_openpose](https://github.com/ildoonet/tf-pose-estimation) model as a API in order to get the 18 COCO - Body keypoints. [Here](https://github.com/sebo313/coco-annotator) is my current work. So far I did the following:

1. Added [tf_openpose](https://github.com/ildoonet/tf-pose-estimation) repo to [backend/Dockerfile](https://github.com/sebo313/coco-annotator/blob/b2255ed57a7adce1be5ce461c6df1bd5ffa25fd0/backend/Dockerfile#L28) 
2. Added tf_openpose model path and keypoint names to [docker-compose.dev.yml](https://github.com/sebo313/coco-annotator/blob/b2255ed57a7adce1be5ce461c6df1bd5ffa25fd0/docker-compose.dev.yml#L59) and [docker-compose.gpu.yml](https://github.com/sebo313/coco-annotator/blob/b2255ed57a7adce1be5ce461c6df1bd5ffa25fd0/docker-compose.gpu.yml#L35) as well as to [backend/config/config.py](https://github.com/sebo313/coco-annotator/blob/b2255ed57a7adce1be5ce461c6df1bd5ffa25fd0/backend/config/config.py#L72)
3. Added [API Route (/'openpose')](https://github.com/sebo313/coco-annotator/blob/b2255ed57a7adce1be5ce461c6df1bd5ffa25fd0/backend/webserver/api/models.py#L94) in order to return the keypoints in COCO-format
4. Wrote the python script [tf_openpose.py](https://github.com/sebo313/coco-annotator/blob/master/backend/webserver/util/tf_openpose.py) which inferences the image and returns body keypoints. 

However, when running `docker-compose -f docker-compose.dev.yml up --build`, i get following error:

````
File "/workspace/webserver/util/tf_openpose.py", line 8, in <module>

from openpose.tf_pose.estimator import TfPoseEstimator

ModuleNotFoundError: No module named 'openpose'
````

So `openpose` is not found which should be git cloned in the [backend/Dockerfile](https://github.com/sebo313/coco-annotator/blob/b2255ed57a7adce1be5ce461c6df1bd5ffa25fd0/backend/Dockerfile#L28) right? I tried to run everything with `docker-compose -f docker-compose.gpu.yml up --build`, but it did not work either. Do you know how to handle this error? 

Are the steps correct in order to add an own API to Coco-Annotator or am I missing something?

As soon as I have the API call built and it is running, I am happy to do a PR.
Thanks!

**Comment by jsbroks** [comment]
If you take a look at the docker file for the webserver, you will notice it is based off of python-env:
```dockerfile
FROM jsbroks/coco-annotator:python-env
```
`python-env` is made from the docker file at `/backend/Dockerfile`. 

Since you can not modify the python-env (as it is on dockerhub), I recommend you place that clone command in the `/backend/webserver/Dockerfile`

Other then that, your steps do seem correct.

**Comment by sebo313** [comment]
Hi @jsbroks thank you very much for this useful hint! All modules are found now and the api reads the image. However the image inference breaks and gives following error:

```
annotator_client | Proxy error: Could not proxy request /model/openpose from localhost:8080 to http://webserver:5000/api/.
annotator_client | See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
annotator_client | 
annotator_message_q | 2020-04-03 11:23:45.806 [warning] <0.2106.0> closing AMQP connection <0.2106.0> (172.19.0.5:41996 -> 172.19.0.2:5672, vhost: '/', user: 'user'):
annotator_message_q | client unexpectedly closed TCP connection
annotator_webserver | [2020-04-03 11:23:45 +0000] [602] [INFO] Booting worker with pid: 602
annotator_message_q | 2020-04-03 11:23:45.802 [warning] <0.2086.0> closing AMQP connection <0.2086.0> (172.19.0.5:41924 -> 172.19.0.2:5672, vhost: '/', user: 'user'):
annotator_message_q | client unexpectedly closed TCP connection
```

Might it be possible that this error is due to wrong json format? My created json ([see here](https://github.com/sebo313/coco-annotator/blob/73931e9b775e7a4d03afbd0f3c2d5d2df6d9688c/backend/webserver/util/tf_openpose.py#L51-L68))could not be formatted as the Annotator expects it to be right? 
Or is it a problem that i name the returned variable "coco" ([see here](https://github.com/sebo313/coco-annotator/blob/73931e9b775e7a4d03afbd0f3c2d5d2df6d9688c/backend/webserver/api/models.py#L102-L107)) similar to to MaskRcnn api?

Another reason for this error might be that I didnt modify the [AnnotateButton.vue](https://github.com/sebo313/coco-annotator/blob/master/client/src/components/annotator/tools/AnnotateButton.vue) file at all... maybe i need to add the return of Openpose keypoint data? Unfortunately i am not familiar at all with vue.js.

Thanks!

**Comment by sebo313** [comment]
Hi @jsbroks, so i am thinking of using your `imantics` module in order to provide the correct COCO-Format to the Annotator. I tried with:

```
    coco_image = im.Image(width=image_w, height=image_h)

    for i in range(len(humans)):
        annotation = im.Annotation(keypoints[i])
        category = im.Category('skeleton')
        coco_image.add(annotation, category=category)

        return coco_image.coco()
```
but it returns me `AssertionError: you must provide a mask, bbox or polygon`. I checked the `imantics` modules and there are no keypoints included right?

**Comment by sebo313** [comment]
@jsbroks  UPDATE: The JSON-formatting is not the problem regarding the this error:

```
annotator_client | Proxy error: Could not proxy request /model/openpose from localhost:8080 to http://webserver:5000/api/.
annotator_client | See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
annotator_client | 
annotator_message_q | 2020-04-03 11:23:45.806 [warning] <0.2106.0> closing AMQP connection <0.2106.0> (172.19.0.5:41996 -> 172.19.0.2:5672, vhost: '/', user: 'user'):
annotator_message_q | client unexpectedly closed TCP connection
annotator_webserver | [2020-04-03 11:23:45 +0000] [602] [INFO] Booting worker with pid: 602
annotator_message_q | 2020-04-03 11:23:45.802 [warning] <0.2086.0> closing AMQP connection <0.2086.0> (172.19.0.5:41924 -> 172.19.0.2:5672, vhost: '/', user: 'user'):
annotator_message_q | client unexpectedly closed TCP connection
```

When returning an empty json it runs smoothly, but when my model runs inference on an image ([see this line of code](https://github.com/sebo313/coco-annotator/blob/73931e9b775e7a4d03afbd0f3c2d5d2df6d9688c/backend/webserver/util/tf_openpose.py#L44)), the error pops up. Is there any **size** or **time** limitations which could cause this error?

**Comment by jsbroks** [comment]
You will probably have to debug furthure to figure out the cause of the issue.

There is a timeout on gunicorn

https://github.com/sebo313/coco-annotator/blob/73931e9b775e7a4d03afbd0f3c2d5d2df6d9688c/backend/webserver/gunicorn_config.py#L11

**Comment by jsbroks** [comment]
@sebo313 did you get it working

**Comment by sebo313** [comment]
Hi @jsbroks I finally got it running! The error was arising because of a bug on the OpenPose code, not on the annotator side :) So thank you so much for helping with this issue!

**Comment by kevkid** [comment]
Hi @sebo361 Could you possibly share your implementation? I am also trying to do the same
