### ISSUE TITLE
coco-annotator rest api

### ISSUE THREAD

**Issue by andrewssobral** [jsbroks/coco-annotator#361]
Hello guys, thanks a lot for this nice project, congrats!

I was trying to use the REST API from coco-annotator but I'm getting some issues, could you help me please? See images below:

![image](https://user-images.githubusercontent.com/483114/80035681-b90ee500-84f0-11ea-8c36-e4db30ce0df3.png)

![image](https://user-images.githubusercontent.com/483114/80035813-f2475500-84f0-11ea-9e34-c947f0c30c11.png)

A second issue is the button [Generate] from the UI is not working as before, no image is downloaded and it doesn't show any issue in the terminal:

![image](https://user-images.githubusercontent.com/483114/80035900-1a36b880-84f1-11ea-8974-3a892f9330d8.png)

**Comment by jsbroks** [comment]
As per #29 web uploads are not supported

**Comment by andrewssobral** [comment]
Thank you @jsbroks for your quick feedback.
Any update about the [Generate] button?
Thanks in advance

**Comment by jsbroks** [comment]
@andrewssobral Generate button is broken due to the undering python lib and changes to googles api in 2020
