### ISSUE TITLE
Hidden label tags are not working

### ISSUE THREAD

**Issue by Sifat-Ahmed** [jsbroks/coco-annotator#368]
Recently I was trying to label a dataset of mine and realized for hidden keypoints, if I select the tag label not visible it doesn't save the tag, rather  it goes back to label visible tag.

any solution?

**Comment by jsbroks** [comment]
I checked on latest, did not have this issue. I created three labels, changed between each and checked.

Are you saving as you go? ctrl+s?

**Comment by jsbroks** [comment]
Inactivity
