### ISSUE TITLE
Support Directories in File Watcher

### ISSUE THREAD

**Issue by linuslofgren** [jsbroks/coco-annotator#374]
## Feature request
Currently the file watcher only supports events on a per-file basis. We were recently in a situation where we wanted to delete a directory of images. Deleting the directory did not delete the images and we had to manually delete them in the database.

From `backend/webserver/watcher.py`
```python
if (
            event.is_directory
            # check if its a hidden file
            or bool(re.search(r'\/\..*?\/', path))
            or not path.lower().endswith(self.pattern)
        ):
            return
```

Detecting changes to directories would be a useful feature when working with large datasets and would mitigate errors arising from users deleting folders instead of deleting every file individually.

If this is deemed to be in the scope of this project I would be willing to create a pull request with an implementation.

**Comment by jsbroks** [comment]
This would definitely be a nice feature and I feel many users would appreciate it
