### ISSUE TITLE
Loading dataset occurs internal server error

### ISSUE THREAD

**Issue by fyang064** [jsbroks/coco-annotator#379]
Something wrong happened when I created a folder in the directory of dataset and tried to put my own images inside my dataset. It showed that annotator_webclient and annotator_workers both have  PermissionError: [Errno 1] Operation not permitted.
I'm running COCO Annotator v0.11.0 on Win 10.

**Comment by jsbroks** [comment]
Use sudo to move the images into the folder

**Comment by fyang064** [comment]
Thank you for the reply!
The problem is still unresolved. I guess something wrong when I tried to operate on Docker, since that every time I tried to create a dataset through annotator_webclient, it occurred "Internal Server Error" which also means that the operation is not permitted. It seems like that all my operations on browser do not work due to permission error. I'm not sure where to begin the right thing.

**Comment by fyang064** [comment]
> Use sudo to move the images into the folder

Thank you for the reply!
The problem is still unresolved. I guess something wrong when I tried to operate on Docker, since that every time I tried to create a dataset through annotator_webclient, it occurred "Internal Server Error" which also means that the operation is not permitted. It seems like that all my operations on browser do not work due to permission error. I'm not sure where to begin the right thing.

**Comment by jsbroks** [comment]
Check the permissions on the folder?
Does the webserver terminal give any more information about the error?

**Comment by fyang064** [comment]
> Check the permissions on the folder?
> Does the webserver terminal give any more information about the error?

After giving the permission of access to the folder, the problem is resolved now. It's kind of weird how the request for permission is triggered.
Anyway, thank you for the help!

**Comment by Sicily-F** [comment]
Hi there,

I know this issue is closed, but I get an internal server error even just trying to create a dataset. I followed all the installation instructions and ran the Windows Powershell as an administrator as well as Docker. I'm completely at a loss!
