### ISSUE TITLE
AnnotateButton for pure Object Detection tasks

### ISSUE THREAD

**Issue by razorx89** [jsbroks/coco-annotator#386]
Currently, the AnnotateButton only imports annotations with segmentations or keypoints:
https://github.com/jsbroks/coco-annotator/blob/2c7b11b998e0ad577753ffd6d046267ba3c1c5f6/client/src/components/annotator/tools/AnnotateButton.vue#L62-L71

However, as far as I understand the COCO data format, a `bbox` with an empty `segmentation` is also a valid COCO annotation. I am currently trying to import object detection annotations from a trained model in order to speed up further annotation efforts. The generated annotations are actually imported as they show up the the list, but have no bbox/geometry associated.

**Comment by razorx89** [comment]
Okay I got it working for now. First, I added a dummy segmentation polygon with all four corner points. Second, I modified the `components/tools/AnnotateButton.vue` to also extract `isbbox` with default `false` from the annotation object and pass it to the `addAnnotation` function in `views/Annotator.vue` and subsequently to the backend API. Would you say that this it the way to go? If yes, then I would be happy to open a PR to push these changes to master.

Further possible improvment: If the segmentation is empty, then one could implicitly assume a bounding box and generate the segmentation polygon on-the-fly. Would be helpful for object detection inference, since several articles on medium propose this format (`bbox: [...]`, `segmentation: []`).

**Comment by jsbroks** [comment]
Submit a PR and Ill take a look, but it sounds good too me. Generating the segmentation won't be hard, plus I just wrote a library for this

**Comment by Andrew-M-Cox** [comment]
Did this get pushed or merged? I'd love to use it too but I don't see it in my AnnotateButton.vue 

If not, would it be possible to get some more details on how you modified the AnnotateButton.vue file?

**Comment by ababino** [comment]
I implemented this [here](https://github.com/ababino/coco-annotator/tree/annotate_bbox). I can submit a PR if @jsbroks and @razorx89 think it's ok.

**Comment by jsbroks** [comment]
@ababino be nice to open a pr for this. I know others would appreciate
