### ISSUE TITLE
Use Mask RCNN

### ISSUE THREAD

**Issue by kk-h-tag** [jsbroks/coco-annotator#387]
I want to use the pth extension, the pytorch model.
Can Coco-annotator only use the h5 extension?

**Comment by jsbroks** [comment]
Only supports h5. But you can setup an endpoint and make it return coco json. Then point the annotator to the url

**Comment by ababino** [comment]
@kk-h-tag I set up an endpoint for this purpose. You can check it [here](https://github.com/ababino/frcnn_endpoint). The default parameters are set to use Faster RCNN, which currently [does not work](https://github.com/jsbroks/coco-annotator/issues/386) with coco-annotator. But it is easy to set it up to use Mask R-CNN, which should work.

**Comment by kk-h-tag** [comment]
@ababino Thanks for your answer.
I will proceed by referring to your answer. :)

**Comment by jitaxis** [comment]
Hi @kk-h-tag, were you able to get it working with Mask R-CNN?
