### ISSUE TITLE
Brush Annotation changes when becoming polygon in Tiny Object Annotation

### ISSUE THREAD

**Issue by arasharchor** [jsbroks/coco-annotator#388]
Hi, 

I am trying to annotate extremely tiny objects and approximation of brush annotation to a polygon makes the annotation inaccurate. How to deactivate this and allow the original annotation to be saved and not the approximated version?

**Comment by jsbroks** [comment]
you will need to change the values for simplify and flatten
https://github.com/jsbroks/coco-annotator/blob/3636297e3278859b98ba8a6752006d2cf4d11136/client/src/components/annotator/Annotation.vue#L518
