### ISSUE TITLE
remove exports

### ISSUE THREAD

**Issue by kevkid** [jsbroks/coco-annotator#392]
Once I have exported my annotations can I delete my exports?

**Comment by jsbroks** [comment]
I'm not really sure what this question is asking. Yes, you can?

**Comment by kevkid** [comment]
@jsbroks can you show how? I could not for the life of me delete them. I looked through the wiki and didn't see how to?

**Comment by jsbroks** [comment]
Could you specify which part or the export youd like to delete? The exported file? The export task?

**Comment by jsbroks** [comment]
Inactive
