### ISSUE TITLE
Run the backend separately

### ISSUE THREAD

**Issue by KhyatiMehta3** [jsbroks/coco-annotator#393]
Hello! 
This is probably a noob question, but I couldn't find any explanatory answer anywhere so I just opened an issue here. 
So I'm looking to make a few changes on the front end, I want some UI changes. 
I know how to implement them, but I'm not finding a way to run docker compose with the code changes that I've made.
Running docker-compose only runs the official image from docker hub.
Is there anyway I can run the code changes I made, through docker-compose?

**Comment by jsbroks** [comment]
https://github.com/jsbroks/coco-annotator/wiki/Getting-Started#Development-Build
