### ISSUE TITLE
Cannot use model under dev mode

### ISSUE THREAD

**Issue by xden2331** [jsbroks/coco-annotator#394]
Following the instruction [176](https://github.com/jsbroks/coco-annotator/issues/176) here.
I can use the model to annotate one image in production mode.
However, when I run the annotator in dev mode and re-follow the instruction, it says
`Cannot read data from URL`.

On the other hand, in the log, I notice
`[2020-07-10 09:09:34 +0000] [230] [INFO] Loaded MaskRCNN model: /models/mask_rcnn_coco.h5`
Keeps appearing. It seems that the webserver is kept being restarted?

Steps to reproduce:
1. Start the annotation in dev mode
2. Open an image, click 'Annotate image'

What I want to do is to modify the backend code. Under the production mode, it seems that the modification is not loaded. I am not sure why. So I switch to the dev mode.

**Comment by jsbroks** [comment]
You could try increasing the timeout of the threads? Not really sure the cause through

**Comment by xden2331** [comment]
> You could try increasing the timeout of the threads? Not really sure the cause through

Here is the log when I click 'Annotate Image'. I have set the timeout in gunicorn_config.py to 120.

annotator_webserver | [2020-07-13 00:46:05 +0000] [11] [DEBUG] POST /api/model/maskrcnn
annotator_webserver | 2020-07-13 00:46:07.545160: W tensorflow/core/framework/allocator.cc:124] Allocation of 67108864 exceeds 10% of system memory.
annotator_webserver | 2020-07-13 00:46:10.236077: W tensorflow/core/framework/allocator.cc:124] Allocation of 67108864 exceeds 10% of system memory.
annotator_webserver | 2020-07-13 00:46:10.651464: W tensorflow/core/framework/allocator.cc:124] Allocation of 67108864 exceeds 10% of system memory.
annotator_webserver | 2020-07-13 00:46:11.116133: W tensorflow/core/framework/allocator.cc:124] Allocation of 67108864 exceeds 10% of system memory.
annotator_webserver | 2020-07-13 00:46:11.395047: W tensorflow/core/framework/allocator.cc:124] Allocation of 67108864 exceeds 10% of system memory.
annotator_message_q | 2020-07-13 00:46:22.776 [warning] <0.806.0> closing AMQP connection <0.806.0> (172.21.0.5:51520 -> 172.21.0.3:5672, vhost: '/', user: 'user'):
annotator_message_q | client unexpectedly closed TCP connection
annotator_message_q | 2020-07-13 00:46:22.788 [warning] <0.836.0> closing AMQP connection <0.836.0> (172.21.0.5:51582 -> 172.21.0.3:5672, vhost: '/', user: 'user'):
annotator_message_q | client unexpectedly closed TCP connection
annotator_client | Proxy error: Could not proxy request /?EIO=3&transport=websocket&sid=76e6ac0d8b0748a2ba17dedd55469307 from localhost:8080 to http://webserver:5000/socket.io.
annotator_client | See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
annotator_client | 
annotator_client | Proxy error: Could not proxy request /model/maskrcnn from localhost:8080 to http://webserver:5000/api/.
annotator_client | See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
annotator_client | 
annotator_webserver | [2020-07-13 00:46:22 +0000] [87] [INFO] Booting worker with pid: 87
annotator_webserver | Using TensorFlow backend.
annotator_webserver | WARNING:tensorflow:From /usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
annotator_webserver | Instructions for updating:
annotator_webserver | Colocations handled automatically by placer.
annotator_webserver | WARNING:tensorflow:From /usr/local/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py:772: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
annotator_webserver | Instructions for updating:
annotator_webserver | Use tf.cast instead.

**Comment by xden2331** [comment]
> > You could try increasing the timeout of the threads? Not really sure the cause through
> 
> Here is the log when I click 'Annotate Image'. I have set the timeout in gunicorn_config.py to 120.
> 
> annotator_webserver | [2020-07-13 00:46:05 +0000] [11] [DEBUG] POST /api/model/maskrcnn
> annotator_webserver | 2020-07-13 00:46:07.545160: W tensorflow/core/framework/allocator.cc:124] Allocation of 67108864 exceeds 10% of system memory.
> annotator_webserver | 2020-07-13 00:46:10.236077: W tensorflow/core/framework/allocator.cc:124] Allocation of 67108864 exceeds 10% of system memory.
> annotator_webserver | 2020-07-13 00:46:10.651464: W tensorflow/core/framework/allocator.cc:124] Allocation of 67108864 exceeds 10% of system memory.
> annotator_webserver | 2020-07-13 00:46:11.116133: W tensorflow/core/framework/allocator.cc:124] Allocation of 67108864 exceeds 10% of system memory.
> annotator_webserver | 2020-07-13 00:46:11.395047: W tensorflow/core/framework/allocator.cc:124] Allocation of 67108864 exceeds 10% of system memory.
> annotator_message_q | 2020-07-13 00:46:22.776 [warning] <0.806.0> closing AMQP connection <0.806.0> (172.21.0.5:51520 -> 172.21.0.3:5672, vhost: '/', user: 'user'):
> annotator_message_q | client unexpectedly closed TCP connection
> annotator_message_q | 2020-07-13 00:46:22.788 [warning] <0.836.0> closing AMQP connection <0.836.0> (172.21.0.5:51582 -> 172.21.0.3:5672, vhost: '/', user: 'user'):
> annotator_message_q | client unexpectedly closed TCP connection
> annotator_client | Proxy error: Could not proxy request /?EIO=3&transport=websocket&sid=76e6ac0d8b0748a2ba17dedd55469307 from localhost:8080 to http://webserver:5000/socket.io.
> annotator_client | See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
> annotator_client |
> annotator_client | Proxy error: Could not proxy request /model/maskrcnn from localhost:8080 to http://webserver:5000/api/.
> annotator_client | See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
> annotator_client |
> annotator_webserver | [2020-07-13 00:46:22 +0000] [87] [INFO] Booting worker with pid: 87
> annotator_webserver | Using TensorFlow backend.
> annotator_webserver | WARNING:tensorflow:From /usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
> annotator_webserver | Instructions for updating:
> annotator_webserver | Colocations handled automatically by placer.
> annotator_webserver | WARNING:tensorflow:From /usr/local/lib/python3.6/site-packages/mask_rcnn-2.1-py3.6.egg/mrcnn/model.py:772: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
> annotator_webserver | Instructions for updating:
> annotator_webserver | Use tf.cast instead.

Solved.
If you run `docker stats`, you can see the 'webserver' takes approximately 80-90% RAM. I set the allocated RAM from 2GB to 3GB, and the 'Annotate image' can be used under dev mode.
Btw, the timeout should also be set to at least 60. It can be set in 'gunicorn_config.py'.
