### ISSUE TITLE
Annotation limit?

### ISSUE THREAD

**Issue by norton-pythian** [jsbroks/coco-annotator#396]
I'm not sure if this is purposefull, but I've tried this on multiple images and it will only save the first 214 annotations and just deletes the remaining. Also after 214 images it doesn't let me go back to the dataset, I have to reload the page. (I don't think 214 would be an actual limit, maybe its a memory issue or something, but that's how many annotations I am able to get up to before it stops working)

edit: seems to be a glitch on one of my datasets, because I was able to get well past that number on another dataset. Although it gets extremely laggy.

**Comment by jsbroks** [comment]
Im really sure why... I've personal done over 214 annotations. What hardware are you on

**Comment by norton-pythian** [comment]
On a different dataset I was able to get 500 annotations with no problem. I'm on a 2019 MacBook Pro (6-core i7, 16GB RAM, Intel graphics 630). Might just be a glitch with that specific image, I really don't know. I split the image up into 3 images (by cropping) and that avoided the issue.
