### ISSUE TITLE
Is there another demo link?

### ISSUE THREAD

**Issue by blackCmd** [jsbroks/coco-annotator#402]
`Demo` link : https://annotator.justinbrooks.ca/

`Demo` link is broken.
How to enter `Demo` site?

**Comment by jsbroks** [comment]
Sadly no, there will be no demo link. I have posted a video that shows installation instructions.

**Comment by blackCmd** [comment]
> Sadly no, there will be no demo link. I have posted a video that shows installation instructions.

ㅠ_ㅠ    
Ok.... Thanks !
