### ISSUE TITLE
Cannot

### ISSUE THREAD

**Issue by fyang064** [jsbroks/coco-annotator#403]

**Comment by fyang064** [comment]
![WeChat Screenshot_20200721183538](https://user-images.githubusercontent.com/44177668/88114064-16aede00-cb81-11ea-94ba-676d9d0ee2f6.png)

**Comment by fyang064** [comment]
No responds after clicking the download button in the webclient

**Comment by jsbroks** [comment]
@fyang064 Check out the video added in the readme on how to export data
