### ISSUE TITLE
Not working with ubuntu 16

### ISSUE THREAD

**Issue by tony-71** [jsbroks/coco-annotator#404]
Hi,

If I try to start v.0.11.1 in Ubuntu 16.04.6 LTS  have the following error:
(py35) root@xxx:~/coco-annotator-master# docker-compose up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

I download the code from https://github.com/jsbroks/coco-annotator/archive/master.zip
and follwed the instruction in https://github.com/jsbroks/coco-annotator/wiki/Getting-Started#Downloading

Best Regards,
Antonio

**Comment by tony-71** [comment]
The problem was with user environment and not because of old Ubuntu version.

Best Regards,
Antonio

**Comment by tianyu-sz** [comment]
I get the same error. Did you resolve it? :)

**Comment by tianyu-sz** [comment]
In the docker-compose.yml file(v0.11.1), I changed the version from "3" to "2", and it seems working :)
