### ISSUE TITLE
salvage corrupted database

### ISSUE THREAD

**Issue by iNLyze** [jsbroks/coco-annotator#406]
A server stopped while ca was running. 
Now I have two problems: 

1. User profiles are lost
2. Datasets won't load anymore

Because of 1. I can't log in as admin anymore. 
Can you give me a hint how I can reset the admin passwd? Which container stores user profiles?
re 2.: Where and how is annotation data stored? I have a new instance of ca running on a different machine. Any chance I could transfer the annotations (without being able to export the usual way)?

**Comment by iNLyze** [comment]
Reading the docker-compose.yml I understand the data is stored in a mongo database and there in a volume that gets mounted to /data/db. I just can not find this volume on the host. Can someone give me a pointer where to find that?

"""docker
  database:
    image: mongo:4.0
    container_name: annotator_mongodb
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "mongodb_data:/data/db"
    command: "mongod --smallfiles --logpath=/dev/null"
    networks:
      - cocoannotator
"""

**Comment by jsbroks** [comment]
https://github.com/jsbroks/coco-annotator/wiki/Implementation#database-volume

If the data is very import you should always back it up.
