### ISSUE TITLE
Error building up docker

### ISSUE THREAD

**Issue by Lee4396** [jsbroks/coco-annotator#408]
I got this weird error when I tried to build the docker on AWS windows machine(docker-compose -f docker-compose.dev.yml up --build):

Building workers
Step 1/5 : FROM jsbroks/coco-annotator:python-env
 ---> 5326b8af1eec
Step 2/5 : WORKDIR /workspace/
ERROR: Service 'workers' failed to build: failed to start service utility VM (createreadwrite): hcsshim::CreateComputeSystem 386c5cf3b42f17761a82aed5cc5f6ab312015574a301d415f94b5c731005da5d_svm: The virtual machine could not be started because a required feature is not installed.
(extra info: {"SystemType":"container","Name":"386c5cf3b42f17761a82aed5cc5f6ab312015574a301d415f94b5c731005da5d_svm","Layers":null,"HvPartition":true,"HvRuntime":{"ImagePath":"C:\\Program Files\\Linux Containers","LinuxInitrdFile":"initrd.img","LinuxKernelFile":"kernel"},"ContainerType":"linux","TerminateOnLastHandleClosed":true})

No clue what is wrong here.

**Comment by jsbroks** [comment]
Not related to coco annotator. something todo with your docker install
https://github.com/docker/labs/issues/490
take a look around on google
