### ISSUE TITLE
How could I remove the option of registering new users?

### ISSUE THREAD

**Issue by bpmsilva** [jsbroks/coco-annotator#409]
In my case, this is a safety issue. I would like to remove the option of registering new users. I do not worry about the aesthetics of the client-side. I just want to avoid possible attacks. How could I do that?

Thanks in advance

**Comment by jsbroks** [comment]
take a look at 

https://github.com/jsbroks/coco-annotator/blob/b5d8394b90b82775bde072f944c8865df43602be/backend/config/config.py#L64

**Comment by CURTLab** [comment]
@jsbroks I have a similar problem. Coco-annotator is already running in production on my server. If I use `docker-compose down` then change `ALLOW_REGISTRATION = False` and `docker-compose up` nothing is changing and new users can still register. Could you maybe help me?
