### ISSUE TITLE
Problem when setting up through docker-compose up

### ISSUE THREAD

**Issue by Rainie-Hu** [jsbroks/coco-annotator#417]
Hi,
I am using Windows 10 Pro to download coco-annotator, then I met an error when executing docker-compose up in command prompt. Could you please help me with it?

annotator_message_q | 2020-08-26 17:15:32.525 [info] <0.708.0> accepting AMQP connection <0.708.0> (172.18.0.5:56478 -> 172.18.0.4:5672)
annotator_message_q | 2020-08-26 17:15:32.536 [info] <0.708.0> connection <0.708.0> (172.18.0.5:56478 -> 172.18.0.4:5672): user 'user' authenticated and granted access to vhost '/'
annotator_workers | [2020-08-26 17:15:32,538: INFO/MainProcess] mingle: searching for neighbors
annotator_message_q | 2020-08-26 17:15:32.608 [info] <0.725.0> accepting AMQP connection <0.725.0> (172.18.0.5:56480 -> 172.18.0.4:5672)
annotator_message_q | 2020-08-26 17:15:32.619 [info] <0.725.0> connection <0.725.0> (172.18.0.5:56480 -> 172.18.0.4:5672): user 'user' authenticated and granted access to vhost '/'
annotator_workers | [2020-08-26 17:15:33,674: INFO/MainProcess] mingle: all alone
annotator_workers | [2020-08-26 17:15:33,779: INFO/MainProcess] celery@f06961f7afa9 ready.
annotator_message_q | 2020-08-26 17:18:32.622 [error] <0.725.0> closing AMQP connection <0.725.0> (172.18.0.5:56480 -> 172.18.0.4:5672):
annotator_message_q | missed heartbeats from client, timeout: 60s

Thanks so much!

Rainie

**Comment by jsbroks** [comment]
Is the application not working? Does the webpage load?

**Comment by angeload** [comment]
Having a similar problem. Application is not working.


annotator_webclient | [2020-10-06 17:38:18 +0000] [6] [INFO] Starting gunicorn 19.9.0
annotator_webclient | [2020-10-06 17:38:18 +0000] [6] [DEBUG] Arbiter booted
annotator_webclient | [2020-10-06 17:38:18 +0000] [6] [INFO] Listening at: http://0.0.0.0:5000 (6)
annotator_webclient | [2020-10-06 17:38:18 +0000] [6] [INFO] Using worker: eventlet
annotator_webclient | [2020-10-06 17:38:18 +0000] [10] [INFO] Booting worker with pid: 10
annotator_webclient | [2020-10-06 17:38:18 +0000] [6] [DEBUG] 1 workers
annotator_webclient | [2020-10-06 17:38:18 +0000] [10] [WARNING] MaskRCNN model is disabled.
annotator_webclient | [2020-10-06 17:38:18 +0000] [10] [WARNING] DEXTR model is disabled.
annotator_webclient | [2020-10-06 17:38:49 +0000] [10] [ERROR] Exception in worker process
annotator_webclient | Traceback (most recent call last):
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
annotator_webclient |     worker.init_process()
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/geventlet.py", line 102, in init_process
annotator_webclient |     super(EventletWorker, self).init_process()
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
annotator_webclient |     self.load_wsgi()
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
annotator_webclient |     self.wsgi = self.app.wsgi()
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
annotator_webclient |     self.callable = self.load()
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
annotator_webclient |     return self.load_wsgiapp()
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
annotator_webclient |     return util.import_app(self.app_uri)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
annotator_webclient |     __import__(module)
annotator_webclient |   File "/workspace/webserver/__init__.py", line 63, in <module>
annotator_webclient |     app = create_app()
annotator_webclient |   File "/workspace/webserver/__init__.py", line 57, in create_app
annotator_webclient |     ImageModel.objects.update(annotating=[])
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/mongoengine/queryset/manager.py", line 37, in __get__
annotator_webclient |     queryset = queryset_class(owner, owner._get_collection())
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/mongoengine/document.py", line 208, in _get_collection
annotator_webclient |     db.client.is_primary:
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 857, in is_primary
annotator_webclient |     return self._server_property('is_writable')
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 689, in _server_property
annotator_webclient |     writable_server_selector)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/pymongo/topology.py", line 224, in select_server
annotator_webclient |     address))
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/pymongo/topology.py", line 183, in select_servers
annotator_webclient |     selector, server_timeout, address)
annotator_webclient |   File "/usr/local/lib/python3.6/site-packages/pymongo/topology.py", line 199, in _select_servers_loop
annotator_webclient |     self._error_message(selector))
annotator_webclient | pymongo.errors.ServerSelectionTimeoutError: No servers found yet
annotator_webclient | [2020-10-06 17:38:49 +0000] [10] [INFO] Worker exiting (pid: 10)
annotator_webclient | [2020-10-06 17:38:50 +0000] [6] [INFO] Shutting down: Master
annotator_webclient | [2020-10-06 17:38:50 +0000] [6] [INFO] Reason: Worker failed to boot.
annotator_webclient exited with code 3

**Comment by jsbroks** [comment]
No thte same issue, please open a new one.

**Comment by ChongMingWei** [comment]
@Rainie-Hu Open your web browser and type 

> http://localhost:5000/

Then you will see the register page for first login.

**Comment by guilhermecorreagv** [comment]
I'm having the same issue, I do docker-compose up and when I try to connect I get this message ``annotator_message_q | missed heartbeats from client, timeout: 60s``, did anyone manage to solve it?
