### ISSUE TITLE
How to view or modify the category id？

### ISSUE THREAD

**Issue by buptlihang** [jsbroks/coco-annotator#418]
Thank you very much for your work.

When I create a category, an id that I can’t see is automatically assigned. Only when I delete this category, I can see its id in undo.

![image](https://user-images.githubusercontent.com/30074778/91432756-c835e300-e894-11ea-81ca-cfac9c67a1f2.png)

And how to convert the segmentation to mask (with png format)?

**Comment by SgtWhiskeyjack** [comment]
@buptlihang did you manage to resolve this? I'm also facing the same problem.

**Comment by jsbroks** [comment]
You can do this in post processing after you export the annotations
