### ISSUE TITLE
export coco error

### ISSUE THREAD

**Issue by holyYodu** [jsbroks/coco-annotator#422]
Thanks for your excellent work! 
When I tried to export COCO json file of the annotated dataset, the processing bar doesn't move and stuck in the middle just as illustrated in the figure below
![image](https://user-images.githubusercontent.com/49020470/92581104-ce2eb980-f2c1-11ea-8f2d-681f69ec9725.png)

**Comment by bpmsilva** [comment]
I had a similar problem, but in my case, it was during import. I had an empty annotation and the program was trying o access a non-existent property. That may also be happening to you. My suggestion is that you click on the tasks tab and see the log of the export task. You'll maybe determine the problematic file and/or annotation. Correct or delete it/them and try to export the annotations again.

Hope that helps

**Comment by holyYodu** [comment]
this is the log of the export task, I can't find any clue about the problem, so I had to switch to other annotation tools, thanks for you works anyway!
```
[09-09-2020 01:26:18] [INFO] Exporting 1 annotations for image 1

[09-09-2020 01:26:18] [INFO] Adding category: monkey

[09-09-2020 01:26:18] [INFO] Beginning Export (COCO Format)
```

**Comment by hyungkwonko** [comment]
Had the exact same issue but solved.

This is how I solved:
1) tab on Tasks
2) click on the detailed information of the task to see where it is stucked, memorize the **final id**
![image](https://user-images.githubusercontent.com/37931902/144754590-1a300906-4368-4b21-b5d9-ce86705623f6.png)

3) get back to the dataset, and sort item by id
![image](https://user-images.githubusercontent.com/37931902/144754649-4d04b999-9ed4-4acb-b4b1-a9b5b9cc29ad.png)

4) find the **final id + 1** and re-annotate it
![Inkedtempsnip_LI](https://user-images.githubusercontent.com/37931902/144754820-8ce89b14-b7b3-4572-adcb-fc8fb63e0984.jpg)

5) export success

Still, I do not understand why it has induced such an issue, as there was not any problem with the annotation of the file.

**Comment by ArseniiPavlov** [comment]
@hyungkwonko, I faced the same problem, and your solution helped me a lot, thank you for sharing that. I had keypoint annotated images, and for invalid images, I noticed a strange keypoint in the top left corner of the image which was not intended to be there.

**Comment by Tianyu-Huang-letsgo** [comment]
@hyungkwonko ,thanks to your solution, I solve my problem! In my Wrong Image_Id Annotations, there are too many bbox and keypoints,I guess the server can't support this amount of data. Anyway, thanks!
