### ISSUE TITLE
No images found in directory.

### ISSUE THREAD

**Issue by Dene33** [jsbroks/coco-annotator#44]
Trying to run coco-annotator in Windows. I create a dataset, and put images to `datasets/dataset_name` No result. `Generate` works fine.

**Comment by jsbroks** [comment]
As stated in the [wiki page](https://github.com/jsbroks/coco-annotator/wiki/Getting-Started#windows):

>Due to limitations of CIFS implementation in Linux kernel, file change events in mounted folders of a host are not propagated to a container by Docker for Windows. You can install [docker-windows-volume-watcher](https://github.com/merofeev/docker-windows-volume-watcher) or move the images into the datasets directory from with in the docker to fix this issue.

**Comment by Dene33** [comment]
Actual wiki page clearly stated what one should 

> move the images into the datasets directory to fix this issue

Sorry, I'm not advanced user of Docker. This action should be somehow done from inside the running container? Could you please describe it in little bit more detail on the actual wiki page. Thank you!

**Comment by jsbroks** [comment]
1. Create an image folder inside the datasets directory called `temp`. Note this will map the directory inside the container to `/data/datasets/temp`.
2. Place folders or images inside this folder (using windows folder explorer)
3. Create an interactive bash shell on the container (annotator must be running).
```bash
$ docker exec -it annotator_flask bash
```
4. Move the folders or images into the proper datasets folder using the interactive bash shell
```bash
$ mv /data/datasets/temp/some_image_folder /data/dataset/SomeDataset/
```

**Comment by Dene33** [comment]
Thank you.
