### ISSUE TITLE
"Authorization required" for any actions

### ISSUE THREAD

**Issue by chitoku** [jsbroks/coco-annotator#451]
Hi,
I cloned this repo and ran the production build with `sudo docker-compose up`, however I always get this "**Authorization required**" message on the bottom left corner of the window everytime I take some action, like creating a dataset.

![image](https://user-images.githubusercontent.com/262161/107839503-2a11d880-6d61-11eb-9220-99d9d34b6911.png)

I can see all 4 containers up and running.

```
$ docker ps
CONTAINER ID   IMAGE                             COMMAND                  CREATED              STATUS              PORTS
                                  NAMES
6ea6e5a48a44   rabbitmq:3                        "docker-entrypoint.s…"   3 seconds ago        Up 2 seconds        4369/tcp, 5671-5672/
tcp, 15691-15692/tcp, 25672/tcp   annotator_message_q
9c35c81cea36   mongo:4.0                         "docker-entrypoint.s…"   7 seconds ago        Up 6 seconds        27017/tcp
                                  annotator_mongodb
b57e262b0158   coco-annotator_webserver          "/bin/sh -c 'gunicor…"   About a minute ago   Up About a minute   0.0.0.0:5000->5000/t
cp                                annotator_webserver
87ece5ed6b5f   coco-annotator_workers            "/bin/sh -c 'celery …"   About a minute ago   Up About a minute   0.0.0.0:5555->5555/t
cp                                annotator_workers
7d711454ad0c   heartexlabs/label-studio:latest   "./tools/run.sh"         About an hour ago    Up About an hour    0.0.0.0:8080->8080/t
cp                                label-studio
```

I'm probably missing some crucial step, and I checked the doc on wiki, but could not find any relevant information.
https://github.com/jsbroks/coco-annotator/wiki/Getting-Started

I appreciate if anybody can point me to the right direction.

**Comment by d-wei-of-sensyn** [comment]
Check if you changed the user account often, on the same browser without closing it. 

Sometimes the logout is not clean, making this happening, on my experience.

**Comment by d-wei-of-sensyn** [comment]
Your docker ps shows that the services started up recently, wich means maybe you need to login again...

**Comment by chitoku** [comment]
It works now, as I guess I waited little longer.
Thank you for the advise!
