### ISSUE TITLE
Export annotations as segmentation masks (as images)

### ISSUE THREAD

**Issue by ekmungi** [jsbroks/coco-annotator#454]
I was wondering how to export segmentation masks (as images) from the annotations from coco-annotator.

**Comment by d-wei-of-sensyn** [comment]
Right now I don't think this feature is supported.  : ) 

You can make web-worker to create the mask img though.

**Comment by ekmungi** [comment]
Thanks. I found a solution from here: https://stackoverflow.com/questions/50805634/how-to-create-mask-images-from-coco-dataset.
