### ISSUE TITLE
Win 10 home + docker tool box

### ISSUE THREAD

**Issue by dumyCq** [jsbroks/coco-annotator#46]
I have recently use win 10 home and docker tool box to install the coco-annotator. 
In development mode, it shows  94% after seal ERROR  Failed to compile with 1 errors17:18:57.
and also in production mode, it shows 
annotator_flask | Error: 'app/gunicorn_config.py' doesn't exist

How can I do with this problem? Since the app/gunicorn_config.py is already in my folder and its name without extension.

**Comment by jsbroks** [comment]
Docker Tools is considered Legacy so I have not tested using it. I have the tested on the following platforms:
- Ubuntu 16
- Ubuntu 18
- Docker for Windows

**Comment by dumyCq** [comment]
I have successfully build it with Ubuntu 16. Thank you so much. Can I just generate a data-set from my local? Since I have a data-set of tumor in .jpeg form, I want to label them through your app.
