### ISSUE TITLE
import json file without segmentation information 

### ISSUE THREAD

**Issue by DP1701** [jsbroks/coco-annotator#494]
Hello all,

I have a json file that have no (x,y) points for segmentation (example: "segmentation": [[]]). But there are bounding boxes ("bbox": [4563.0, 346.0, 349.0, 347.0]). When I import this file, the categories are recognized but the bounding boxes are not displayed. Is there a way to display them in the viewer?

**Comment by awarebayes** [comment]
same issue

**Comment by ghazalli** [comment]
Hi, i'm facing the same issue, any idea how to solved this?
