### ISSUE TITLE
Could you please provide the Dockerfile for the image in dockerhub?

### ISSUE THREAD

**Issue by snachx** [jsbroks/coco-annotator#497]
I want to deploy coco-annotator in k8s, so I have to make some changes and build images from scratch.

backend/webserver/Dockerfile shows that the webserver image is built from jsbroks/coco-annotator:python-env

build_gpu.sh shows that the jsbroks/coco-annotator:python-env image is built from tensorflow/tensorflow:1.14.0-gpu-py3

I'v checked the coco-annotator:webserver-latest, there isn't any cuda stuff in it.

Did I misunderstand the process of image building?

**Comment by snachx** [comment]
I've managed to figure it out from the output of docker history command

**Comment by jsbroks** [comment]
Please summarize your findings here for others

**Comment by hubutui** [comment]
It seems jsbroks/coco-annotator:python-env provides no GPU support, am I right?

**Comment by snachx** [comment]
The Dockerfile of coco-annotator:python-env on dockerhub is something like this without GPU support:

FROM python:3.6.8

WORKDIR /workspace/

COPY ./requirements.txt .

RUN pip install -r requirements.txt &&     pip install gunicorn[eventlet]==19.9.0 &&     pip install pycocotools

RUN git clone --single-branch --depth 1 https://github.com/matterport/Mask_RCNN.git /tmp/maskrcnn &&     cd /tmp/maskrcnn &&     pip install -r requirements.txt &&     python3 setup.py install

RUN git clone --single --depth 1 https://github.com/jsbroks/dextr-keras.git /tmp/dextr &&     cd /tmp/dextr &&     pip install -r requirements.txt &&     python setup.py install

**Comment by hubutui** [comment]
@snachx You're right, but jsbroks/coco-annotator:python-env is built about 2 years ago. We could not get the same result when we run `pip install -r requirements.txt`.
For some reason I don't know, the GPU version docker container fail to save the image in to mongodb, see #504.
