### ISSUE TITLE
Automatically create categories, datasets on startup from file(s)/config

### ISSUE THREAD

**Issue by matt-deboer** [jsbroks/coco-annotator#50]
**Feature request**: It would be nice to allow the workflow of pre-defining a bunch of categories and pre-existing datasets on startup. 

I my envisioned use-case, I would volume-mount an existing datasets folder, provide some sort of manifest file containing all the categories that should exist, and a list of datasets that should be automatically created/imported (or maybe just create datasets for all the top-level directories under the `/datasets` folder).

This would allow me to easily migrate from other existing annotation tools to **coco-annotator** with minimal effort. 

To stretch this a bit further, it would be nice if **coco-annotator** could also automatically import annotations created by these other tools (VOC format, YOLO format, etc.)

**Comment by matt-deboer** [comment]
Your updates work fine for my use case. Thanks much.

**Comment by jsbroks** [comment]
@matt-deboer I'm working on a library for converting between annotation formats which could then be used for the annotator.

Any contributors would be great.

https://github.com/jsbroks/imantics
