### ISSUE TITLE
Allow ad hoc categories to be created when creating dataset

### ISSUE THREAD

**Issue by matt-deboer** [jsbroks/coco-annotator#51]
**Enhancement**: it would be useful if **coco-annotator** allowed automatic creation of a list of categories at dataset creation time, such that any categories typed into the free-form list would be created if they do not already exist.

**Comment by jsbroks** [comment]
How do you purpose the user interface to looks? Maybe having a test box the user could type into to add items to the list of categories?

**Comment by jsbroks** [comment]
Something like this: https://github.com/voerro/vue-tagsinput
