### ISSUE TITLE
Propagate annotations to next/previous

### ISSUE THREAD

**Issue by matt-deboer** [jsbroks/coco-annotator#52]
**Feature Request**: It would be helpful if there were a capability to propagate all of the annotations on the current image to the next or previous image.

When annotating images that come from frames of a video sequence, often many of the annotations remain static from one frame to the next, with only a few annotations changing for objects that have moved. 

Perhaps there could be some additional buttons next to the arrows in the upper right of the Annotator view which would trigger this functionality.

**Comment by jsbroks** [comment]
I like this (you have some great ideas!).

Instead of the next or previous image, there should be an input text in the settings menu (settings icon on the left toolbar) where the user can type the id of an image and its corresponding annotations to copy. This way making it more general in case it is not in the proper order.

**Comment by matt-deboer** [comment]
Wait--one question: if it's in the settings dialog, do you expect to persist the id of the image that annotations were copied from? 

I was thinking this is more of a one-time thing--especially since some of the copied annotations may have to be deleted/modified....

**Comment by jsbroks** [comment]
You would enter the id of the image you would like to copy annotations from. Then it pull those annotations from the database and apply all of them the current image. 
From here, using the current tools you can modify the the annotations.

**Comment by matt-deboer** [comment]
Yeah, I understand that part; what seems a little strange is that things in the 'settings' panel are persistent things. Should this 'copy annotations from image id' thing be in a separate modal dialog?

**Comment by jsbroks** [comment]
Yes, you have a good point. Maybe it can be its own button on the left toolbar.

**Comment by matt-deboer** [comment]
@jsbroks ok; take a look at #55 ...thoughts?
