### ISSUE TITLE
Categories ID is not cleared after Fully Deletion

### ISSUE THREAD

**Issue by mo-alaa** [jsbroks/coco-annotator#531]
I created multiple categories (about 31) then I deleted them (fully deletion) , and when I created a new category, `its id was 32 !`

I guess this has something with the nextId that I found in the database at flask.mongoengine.counters 

![image](https://user-images.githubusercontent.com/41386480/147874632-c0870961-49dd-4c6f-b32a-646d3298b4ac.png)

**Comment by f416720001** [comment]
It's normal... 

You can try to modify it, but this way I do not recommend

**Comment by mo-alaa** [comment]
@f416720001  Shouldn't there be something that resets the index of the categories when we delete some?

**Comment by f416720001** [comment]
@mo-alaa Delete is a dangorous behavior~
coco annotator is using a column to record it!

```json
deleted: true
```
so~ All counters point the last index is the best practice.

**Comment by mo-alaa** [comment]
Thanks I got your point, I will close this issue for now.
