### ISSUE TITLE
Order dataset images alphabetically by image name

### ISSUE THREAD

**Issue by matt-deboer** [jsbroks/coco-annotator#58]
**Enhancement**: For datasets which originate from video sequences, it is useful to preserve the original ordering of frames. It would be nice if the images are presented in the UI in alphabetic by image name. 

Video slicers (e.g., ffmpeg) are going to produce video files named sequentially, and preserving alphabetic ordering of the file names will present them for annotation in their original order.

**Comment by jsbroks** [comment]
Strange, this should already be [implemented](https://github.com/jsbroks/coco-annotator/blob/79d1caa031e989d81a86135bb608891dc35f8baa/app/api/datasets.py#L208).

**Comment by matt-deboer** [comment]
My mistake..I was looking at image ids.
