### ISSUE TITLE
How to add a button to customize UI?

### ISSUE THREAD

**Issue by ravijo** [jsbroks/coco-annotator#596]
On the annotation page, I would like to add a "disable all" button to unselect all masks at once. The JS code is straightforward:

```js
let ann_icons = document.getElementsByClassName("fa fa-eye annotation-icon");
for(ann_icon of ann_icons){ann_icon.click();}
```

Let me know, how to add such a button.

Thanks

**Comment by SixK** [comment]
Well, not sure to understand exactly what you need.
There is already a button  to mask all annotations at once in the left panel (eye button).

If you want to add a button in that left panel, you first need to duplicate and then modify a tool file from this path :
client/src/components/annotator/tools/

Then add necessary code to load and handle the new button here : client/src/views/Annotator.vue

If you want to add a button in right panel, have a look at "<Category" tag in client/src/views/Annotator.vue.
You may have to add a button around/near this tag.

**Comment by ravijo** [comment]
Thanks @SixK for the suggestions.
