### ISSUE TITLE
"Undo last action" operation for brush, wand, and polygon

### ISSUE THREAD

**Issue by LoudeNOUGH** [jsbroks/coco-annotator#60]
Related to #18 
Only Eraser is capable of fixing the incorrect action, so undo operation for brush, wand, and polygon is necessary

**Comment by jsbroks** [comment]
All options have the ability to undo the last action. But the tool icon does not seem to be working. If you us the hotkey ctrl+z it should undo your last action.

**Comment by jsbroks** [comment]
Due to author inactivity, I will be closing this issue. A fix for the undo icon has been committed.

**Comment by luxedo** [comment]
I have this issue occasionally but I can't reproduce it. When this happens I also can't disable the tool I'm using by pressing ESC, and sometimes the lines of the polygon tool stays in the screen, even though I start a new polygon.

There's no errors neither in the server nor in the browser.

I fix the problem by reloading the page.
