### ISSUE TITLE
Broken "API" menu link

### ISSUE THREAD

**Issue by gaellafond** [jsbroks/coco-annotator#69]
I checked out the project and built it using:
```docker-compose up```

The system seems to be working. I can access the client using the URL:
```http://localhost:8080```

When I click the "API" link from the top menu, I get a white page and an error in the JavaScript console:
URL: http://localhost:8080/api
Error:
```
Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload (api:75)
```

The system tries to load the following JS file:
```http://localhost:8080/swaggerui/swagger-ui-bundle.js```
but the URL returns an HTML page saying JS must be enabled. If I go to that URL using my web browser, I get redirected to:
```http://localhost:8080/swaggerui/swagger-ui-bundle.js#/```
which shows the same page as:
```http://localhost:8080```

**Comment by gaellafond** [comment]
I just realised that the link is supposed to redirect to the "flask" app, which is on a different port.

The link in the menu should be change from:
```http://localhost:8080/api```
to
```http://localhost:5000/api```

**Comment by jsbroks** [comment]
You are using the development. Ands the client is hosted on a different thread then then the frontend. This allows for the client to be hot reloaded. 

If you dont plan on developing I recommend you use the [production build](https://github.com/jsbroks/coco-annotator/wiki/Getting-Started#Production-Build).

**Comment by gaellafond** [comment]
Thanks Justin,
We are planning to modify the app to fit our needs better. Thanks for your answer, I didn't know about that difference between the build profiles.

**Comment by jsbroks** [comment]
@gaellafond enjoy! Also if you would like to share some ideas, I am always looking for contributors.
