### ISSUE TITLE
current master uploads polygons' points with negative 'y' values

### ISSUE THREAD

**Issue by matt-deboer** [jsbroks/coco-annotator#89]
As of yesterday, new annotations' points seem to be uploaded with negative values for their 'y' dimension, resulting in a segmentation that gets clipped for being outside the bounds (when it is clearly not).

Here's a snipping of the `segments` sent from the client:
```
segments: [[[113.6, -240.3], [0, 0], [0, 0], 7], [[228, -241], [0, 0], [0, 0], 7],…]
0: [[113.6, -240.3], [0, 0], [0, 0], 7]
1: [[228, -241], [0, 0], [0, 0], 7]
2: [[211.4, -234.8], [0, 0], [0, 0], 7]
3: [[211.4, -225.1], [0, 0], [0, 0], 7]
4: [[233.6, -226.5], [0, 0], [0, 0], 7]
5: [[239.8, -222.3], [0, 0], [0, 0], 7]
6: [[242.6, -192.5], [0, 0], [0, 0], 7]
7: [[237.7, -78.7], [0, 0], [0, 0], 7]
8: [[96.9, -68.3], [0, 0], [0, 0], 7]
9: [[85.2, -197.3], [0, 0], [0, 0], 7]
10: [[112.2, -241], [0, 0], [0, 0], 7]
```

I haven't tracked down the root cause yet...

**Comment by matt-deboer** [comment]
It seems that on a mouseDown event, `event.point` contains strange values (seemingly relative to some reference point on the lower-left of the screen?), while `event.downPoint` contains the usual/correct mouse coordinates...
@jsbroks are you seeing anything like this?

**Comment by jsbroks** [comment]
It has to do with PaperJS, by default the origin is located in the center of the image so it but not be getting converted for some reason. Ill look into it later today.

**Comment by matt-deboer** [comment]
hmm..ok; good to know. 

And no, for me it happens on newly-created polygons as well, which shouldn't interact with the select tool, right?...(I simply complete the polygon, then click the Save button)

I'm noticing these points not being converted; instead, they're being "clamped" out of the segmentation in the `paperjs_to_coco` method...

**Comment by jsbroks** [comment]
paperjs_to_coco only reads segments in `[[x1,y1], [x2,y2], ...]` for some reason the export is including the cruve data but settings its value to zero.

**Comment by jsbroks** [comment]
The latest commit fixed the issue for me. Test it out and get back to me.

**Comment by matt-deboer** [comment]
ok; will have a look...

**Comment by matt-deboer** [comment]
seems to be resolved.
