### ISSUE TITLE
Image locking

### ISSUE THREAD

**Issue by bencevans** [jsbroks/coco-annotator#94]
Feature...

Lock images when a user opens an image and release after a time period or a user has finished editing an image to ensure others aren't duplicating work.

**Comment by trinath503** [comment]
In the latest code, image locking feature is missing, Multiple user can do annotations, tool is merging all the annotations.
Seems like image lock is working?

**Comment by jsbroks** [comment]
The time lock doesnt fully disable users from annotating the image. It just shows on the datasset image page if a user is annotating

**Comment by trinath503** [comment]
Can we display the image "Being annotated by the user message" on the canvas also (on open image also), because people will be using next and previous button so they can not know whether it been annotated by another user or not?

**Comment by jsbroks** [comment]
An oversight on my part, my bad. Could you please open anyother issue
