### ISSUE TITLE
occasionally, loading an image displays none of its annotations

### ISSUE THREAD

**Issue by matt-deboer** [jsbroks/coco-annotator#98]
Occasionally, (maybe 5-10% of the time) when navigating to the next or previous image in a dataset, the image loads with no annotations shown in the paperjs window.

This seems like a client-side race condition; no errors occur in the browser console, and it can always be resolved by refreshing the page.

Clicking Hide All/Show All has no effect on the page when it happens to load in this state.

I have not yet determined root cause..

**Comment by jsbroks** [comment]
Strange, I've never encountered this

**Comment by jsbroks** [comment]
For sure a client race.

Ethier the data is getting loaded so fast the annotations are behind the image or the data loads to fast before the papers instance is initialized

**Comment by jsbroks** [comment]
Found the cases. If you do any `mousewheel` action well the image is loading it causes the annotations to fail.
